const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),{create}=require('./host-model.cjs');
const fields=['reverse','manual'];
const cases=[[false,false],[true,true],[0,false],[1,true],['false',false],['true',true],['OFF',false],['on',true],['unchecked',false],['checked',true],[' 0.0 ',false],['1.00',true],['0e0',false],['1e0',true],[[0],false],[[1],true],[{value:false},false],[{value:'off'},false],[{value:'on'},true]];
for(const layout of ['compact','legacy'])for(const field of fields)for(const [input,expected] of cases){const e=create();e.comp.add('text').selected=true;const r=e.rpc({action:'apply',id:'counter',layout,params:{[field]:input}});assert.equal(r.changed,1,r.message);const l=e.comp.selectedLayers[0];if(layout==='legacy')assert.equal(l.fx.property('MA2 '+field).property(1).value,expected?1:0);const loaded=e.rpc({action:'load'});assert.equal(loaded.params[field],expected);assert.equal(e.rpc({action:'update',id:'counter',params:loaded.params}).changed,1);}
for(const bad of ['', 'maybe',2,-1,[],[0,1],{}, {value:false,other:true}]){const e=create();e.comp.add('text').selected=true;const r=e.rpc({action:'apply',id:'counter',params:{reverse:bad}});assert.equal(r.ok,false);assert(r.message.includes('received'));assert(r.message.includes('panel parameter'));assert.equal(e.comp.numLayers,1);}
// Real host values can be boxed; this is deliberately not serialized through JSON first.
for(const [native,expected] of [[new Number(0),false],[new Number(1),true],[new Boolean(false),false],[new String('0.0'),false],[.25,false],[.5,false],[.75,true]]){const e=create();e.comp.add('text').selected=true;e.rpc({action:'apply',id:'counter',layout:'legacy',params:{}});const l=e.comp.selectedLayers[0];l.fx.property('MA2 reverse').property(1).value=native;const r=e.rpc({action:'load'});assert.equal(r.ok,true,r.message);assert.equal(r.params.reverse,expected);}
{const e=create();e.comp.add('text').selected=true;e.rpc({action:'apply',id:'counter',layout:'legacy',params:{}});e.comp.selectedLayers[0].fx.property('MA2 reverse').property(1).value='broken';const r=e.rpc({action:'load'});assert.equal(r.ok,false);assert(r.message.includes('AE control'));assert(r.message.includes('broken'));}
console.log('PASS: Reverse/Manual checkbox normalization and invalid-input guards.');
