const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright'),assert=require('node:assert/strict'),path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']}),page=await browser.newPage({viewport:{width:380,height:850}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{window.requests=[];const bridge={isAvailable:()=>true,isReady:()=>true,call:async a=>{window.requests.push(a);return a.action==='status'?{ok:true,composition:'Curve test',selected:1,version:'Mock',hostVersion:'test'}:{ok:true,changed:1,message:'Curve applied'};}};Object.defineProperty(window,'MotionAstraBridge',{get:()=>bridge,set(){}});});
await page.goto(require('node:url').pathToFileURL(path.resolve(__dirname,'../index.html')).href);await page.locator('[data-workspace="Motion"]').click();await page.locator('[data-tab="Curve"]').click();assert(await page.locator('#curve-graph').isVisible());assert.equal(await page.locator('#curve-presets button').count(),8);
const thumbs=await page.locator('#curve-presets button').evaluateAll(buttons=>buttons.map(b=>{const v=JSON.parse(b.dataset.curve);return {actual:b.querySelector('.curve-thumb-path').getAttribute('d'),expected:'M12 64 C'+(12+v[0]*76)+' '+(64-v[1]*56)+' '+(12+v[2]*76)+' '+(64-v[3]*56)+' 88 8'};}));
thumbs.forEach(t=>assert.equal(t.actual,t.expected));assert.equal(new Set(thumbs.map(t=>t.actual)).size,8);
await page.locator('#curve-presets button',{hasText:'Snappy'}).click();assert.equal(await page.locator('#curve-presets button.active').textContent(),'Snappy');assert.equal(await page.locator('#curve-x1').inputValue(),'0.7');await page.locator('#curve-apply').click();await page.waitForFunction(()=>!document.querySelector('#curve-apply').disabled);assert.deepEqual(await page.evaluate(()=>requests.find(x=>x.name==='curve').curve),[.7,0,.85,1]);
await page.locator('#curve-x1').fill('0.95');assert(await page.locator('#curve-apply').isDisabled());await page.locator('#curve-x1').fill('0.6');await page.locator('#curve-h1').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#curve-x1').inputValue(),'0.61');
const h=await page.locator('#curve-h1').boundingBox();await page.mouse.move(h.x+h.width/2,h.y+h.height/2);await page.mouse.down();await page.mouse.move(h.x-30,h.y-30);await page.mouse.up();assert(Number(await page.locator('#curve-y1').inputValue())>0);
await page.locator('#theme-toggle').click();assert.equal(await page.locator('html').getAttribute('data-theme'),'light');await page.locator('.curve-scroll').evaluate(e=>e.scrollTop=0);await page.waitForTimeout(250);await page.screenshot({path:'/tmp/motionastra-curve-light.png'});await page.reload();assert.equal(await page.locator('html').getAttribute('data-theme'),'light');await page.locator('[data-workspace="Motion"]').click();await page.locator('[data-tab="Curve"]').click();assert(Number(await page.locator('#curve-y1').inputValue())>0);await page.locator('#theme-toggle').click();await page.waitForTimeout(250);await page.screenshot({path:'/tmp/motionastra-curve-dark.png'});
for(const width of [300,380,768,1200]){await page.setViewportSize({width,height:650});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Overflow '+width);const a=await page.locator('.curve-actions').boundingBox(),f=await page.locator('footer').boundingBox();assert(a.y+a.height<=f.y+1);}
const values=await page.evaluate(()=>[0,.25,.5,.75,1].map(x=>MotionCurve.valueAt(x,[1/3,1/3,2/3,2/3])));values.forEach((v,i)=>assert(Math.abs(v-i/4)<1e-7));assert.deepEqual(errors,[]);
const offline=await browser.newPage();await offline.goto(require('node:url').pathToFileURL(path.resolve(__dirname,'../catalog.html')).href);await offline.locator('[data-workspace="Motion"]').click();await offline.locator('[data-tab="Curve"]').click();assert(await offline.locator('#curve-apply').isDisabled());await browser.close();console.log('PASS: curve presets, numeric/pointer/keyboard editing, Apply payload, validation, theme/curve persistence, responsive action footer and offline guard.');})().catch(e=>{console.error(e);process.exit(1);});
