const assert=require('node:assert/strict'),vm=require('node:vm'),{create}=require('./host-model.cjs'),data=require('../presets.json');
function leaves(g,out=[]){for(let i=1;i<=g.numProperties;i++){const p=g.property(i);if(p.expression)out.push(p);if(p.numProperties)leaves(p,out);}return out;}
// Simulated scalar numeric lookup tests the reported dimension failure; not an AE emulation.
function evaluate(l,p,time,scalarLookup){const context={Math,time,inPoint:l.inPoint,thisComp:{width:960,height:540,frameDuration:1/30},thisLayer:{width:960,height:540},value:p.value,textIndex:3,textTotal:10,text:{sourceText:'MotionAstra'},seedRandom(){},random(a,b){return a===undefined?.5:b===undefined?a*.5:(a+b)/2;},createPath(points){points.forEach(v=>v.forEach(n=>assert(Number.isFinite(n),'Invalid path point')));return points;},marker:{numKeys:l.markers.numKeys,key(i){return {time:l.markers.keyTime(i),parameters:l.markers.keyValue(i).getParameters()};}},effect(name){return index=>{const fx=l.fx.property(name);if(!fx)throw Error('Missing effect '+name);const x=fx.property(index);if(scalarLookup&&fx.matchName==='ADBE Color Control'&&index===1)return {value:0};return {value:x.value,numKeys:x.numKeys,key(i){return {time:x.keyTime(i)};},valueAtTime(t){if(!x.numKeys)return x.value;if(t<=x.keyTime(1))return x.keyValue(1);for(let i=2;i<=x.numKeys;i++)if(t<=x.keyTime(i)){const f=(t-x.keyTime(i-1))/(x.keyTime(i)-x.keyTime(i-1));return x.keyValue(i-1)*(1-f)+x.keyValue(i)*f;}return x.keyValue(x.numKeys);}};}}};return vm.runInNewContext(p.expression,context);}
for(const mode of [0,1,2,3])for(const scalarLookup of [false,true])for(const r of data.presets){const e=create();if(r.category==='Text')e.comp.add('text').selected=true;assert.equal(e.rpc({action:'apply',id:r.id,params:{loopMode:mode,color1:'#112233',color2:'#e62a44',color3:'#33bb88',tint:'#4488ee'}}).changed,1);const l=e.comp.selectedLayers[0],duration=r.parameters.find(x=>x.id==='duration').default;for(const p of leaves(l)){let end,after;for(const f of [0,.25,.5,1,2]){let out;try{out=evaluate(l,p,l.inPoint+duration*f,scalarLookup);}catch(error){throw Error(r.id+' '+p.name+': '+error.message);}if(p.matchName==='ADBE Ramp-0002'||p.matchName==='ADBE Ramp-0004'||p.matchName==='ADBE Tint-0001'||p.matchName==='ADBE Tint-0002'){assert(Array.isArray(out)&&out.length===4,r.id+' '+p.name+' must return RGBA');out.forEach(v=>assert(Number.isFinite(v)));const key=p.matchName==='ADBE Ramp-0002'?(l.fx.property('MA2 color2')?'color2':'tint'):p.matchName==='ADBE Ramp-0004'?'color3':p.matchName==='ADBE Tint-0001'?'color1':'color2';const control=l.fx.property('MA2 '+key);if(control)assert.equal(JSON.stringify(out),JSON.stringify(control.property(1).value),r.id+' color must match chosen RGBA');}if(typeof out==='number')assert(Number.isFinite(out),r.id+' '+p.name);if(f===1)end=out;if(f===2)after=out;}if(mode===1||mode===3)assert.equal(JSON.stringify(end),JSON.stringify(after),r.id+' Cycle should repeat at whole durations');}
}
console.log('PASS: all new recipe expressions evaluated at five times; finite paths/scalars; all loop modes and color binding. Native pixel rendering is not modeled.');

for(const r of data.presets.filter(r=>r.category==='Background')){const e=create();assert.equal(e.rpc({action:'generateBackground',id:r.id,params:{static:true,reverse:true,manual:true,progress:80}}).changed,1);const l=e.comp.selectedLayers[0];for(const p of leaves(l))assert.equal(JSON.stringify(evaluate(l,p,l.inPoint,false)),JSON.stringify(evaluate(l,p,l.inPoint+10,false)),r.id+' static mode must not move');}
console.log('PASS: static backgrounds remain unchanged over time, including manual/reverse overrides.');
