const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path'),{create}=require('./host-model.cjs'),root=path.resolve(__dirname,'..');
const data=JSON.parse(fs.readFileSync(root+'/fx-tools.json')),defaults=r=>Object.fromEntries(r.parameters.map(p=>[p.id,p.default]));
const client={window:{}};vm.runInNewContext(fs.readFileSync(root+'/js/fx-tools-data.js','utf8'),client);assert.equal(JSON.stringify(client.window.MA_FXTOOLS),JSON.stringify(data));
for(const kind of ['text','shape','solid','video'])for(const r of data.effects.filter(r=>r.id!=='glass')){const e=create(),l=e.comp.add(kind);l.selected=true;l.comment='Personal notes';l.fx.addProperty('ADBE Fill').name='User Fill';const count=e.comp.numLayers,p=defaults(r);
let result=e.rpc({action:'fxTools',operation:'apply',id:r.id,params:p});assert.equal(result.changed,1,result.message);assert.equal(e.comp.numLayers,count);assert.equal(l.fx.numProperties,5);const identities=l.fx.items.slice();assert.equal(e.rpc({action:'fxTools',operation:'apply',id:r.id,params:p}).changed,1);assert.equal(l.fx.numProperties,5);assert.deepEqual(l.fx.items,identities);
const loaded=e.rpc({action:'fxTools',operation:'load',id:r.id});assert.deepEqual(loaded.params,p);const edited={...p};if(r.id==='prism'){edited.colorA='#12ab34';edited.animate=true;edited.radial=true;}else {edited.tint=true;edited.color='#12ab34';edited.intensity=2;}
assert.equal(e.rpc({action:'fxTools',operation:'update',id:r.id,params:edited,target:loaded.target}).changed,1);const color=l.fx.property(r.id==='prism'?'MAFT prism | gradient':'MAFT bloom | source tint').property(r.id==='prism'?'ADBE Ramp-0002':'ADBE Fill-0002').value;assert.deepEqual(Array.from(color),[18/255,171/255,52/255,1]);
if(r.id==='prism'){const ramp=l.fx.property('MAFT prism | gradient');for(const key of ['ADBE Ramp-0001','ADBE Ramp-0003']){const expr=ramp.property(key).expression;const evaluate=time=>vm.runInNewContext(expr,{time,inPoint:1.5,sourceRectAtTime:()=>({left:-20,top:-50,width:400,height:100})});const a=Array.from(evaluate(1.5)),b=Array.from(evaluate(1.5+edited.duration));assert.equal(a.length,2);assert(a.every(Number.isFinite));a.forEach((v,i)=>assert(Math.abs(v-b[i])<1e-7));assert.notDeepEqual(a,Array.from(evaluate(3.5)));}}
assert.equal(e.rpc({action:'fxTools',operation:'remove',id:r.id,target:loaded.target}).changed,1);assert.equal(l.fx.numProperties,1);assert.equal(l.fx.property(1).name,'User Fill');assert.equal(l.comment,'Personal notes');}
{const e=create(),l=e.comp.add('text');l.selected=true;for(const r of data.effects.filter(r=>r.id!=='glass'))assert.equal(e.rpc({action:'fxTools',operation:'apply',id:r.id,params:defaults(r)}).changed,1);assert.equal(l.fx.numProperties,8);assert.equal(e.rpc({action:'fxTools',operation:'remove',id:'prism'}).changed,1);assert.equal(l.fx.numProperties,4);assert(e.rpc({action:'fxTools',operation:'load',id:'bloom'}).ok);assert.equal(e.rpc({action:'tool',name:'remove'}).changed,1);assert.equal(l.fx.numProperties,0);assert.equal(l.comment,'');}
{const e=create(),l=e.comp.add('text');l.selected=true;const p=defaults(data.effects[0]);assert.equal(e.rpc({action:'fxTools',operation:'apply',id:'prism',params:{...p,colorA:'broken'}}).ok,false);assert.equal(l.fx.numProperties,0);assert.equal(e.rpc({action:'fxTools',operation:'update',id:'prism',params:p}).changed,0);assert.equal(l.fx.numProperties,0);assert.equal(e.rpc({action:'fxTools',operation:'apply',id:'prism',params:p}).changed,1);const loaded=e.rpc({action:'fxTools',operation:'load',id:'prism'});l.selected=false;const other=e.comp.add('text');other.selected=true;assert.equal(e.rpc({action:'fxTools',operation:'update',id:'prism',params:p,target:loaded.target}).ok,false);assert.equal(other.fx.numProperties,0);other.selected=false;l.selected=true;l.locked=true;assert.equal(e.rpc({action:'fxTools',operation:'remove',id:'prism'}).changed,0);l.locked=false;const radius=l.fx.property('MAFT prism | glow').property('ADBE Glo2-0002');radius.setValueAtTime(0,30);assert.equal(e.rpc({action:'fxTools',operation:'update',id:'prism',params:p}).changed,0);assert.equal(radius.numKeys,1);}
// Native failures must undo partial writes and remove partially created effects.
{const e=create(),l=e.comp.add('text');l.selected=true;const p=defaults(data.effects[1]);assert.equal(e.rpc({action:'fxTools',operation:'apply',id:'bloom',params:p}).changed,1);const first=l.fx.property('MAFT bloom | core').property('ADBE Glo2-0004'),bad=l.fx.property('MAFT bloom | halo').property('ADBE Glo2-0004'),before=first.value,write=bad.setValue;let once=true;bad.setValue=function(v){if(once){once=false;throw Error('Injected native write failure');}write.call(this,v);};const r=e.rpc({action:'fxTools',operation:'update',id:'bloom',params:{...p,intensity:3}});assert.equal(r.changed,0);assert.equal(first.value,before);assert.equal(l.fx.numProperties,4);assert(r.message.includes('restored'));}
{const e=create(),l=e.comp.add('text');l.selected=true;const add=l.fx.addProperty.bind(l.fx);let n=0;l.fx.addProperty=name=>{if(++n===3)throw Error('Unavailable native effect');return add(name);};const r=e.rpc({action:'fxTools',operation:'apply',id:'bloom',params:defaults(data.effects[1])});assert.equal(r.changed,0);assert.equal(l.fx.numProperties,0);assert.equal(l.comment,'');}
console.log('PASS: extensible FXTools registry; two effects across four layer types; no duplicates, RGBA colors, rotation loops, stacking, guarded updates, owned cleanup and native-error rollback.');
