const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright'),assert=require('node:assert/strict'),path=require('node:path'),{create}=require('./host-model.cjs');
(async()=>{const e=create(),l=e.comp.add('text');l.selected=true;const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']}),page=await browser.newPage({viewport:{width:380,height:850}}),errors=[];page.on('pageerror',x=>errors.push(x.message));await page.exposeFunction('hostRpc',a=>e.rpc(a));await page.addInitScript(()=>{const bridge={isAvailable:()=>true,isReady:()=>true,call:async a=>{const r=await window.hostRpc(a);if(!r.ok)throw Error(r.message);return r;}};Object.defineProperty(window,'MotionAstraBridge',{get:()=>bridge,set(){}});});
await page.goto(require('node:url').pathToFileURL(path.resolve(__dirname,'../index.html')).href);await page.locator('[data-tab="FXTools"]').click();assert.equal(await page.locator('.ft-card').count(),3);await page.locator('.ft-card').first().getByText('Customize',{exact:true}).click();assert(await page.locator('#ft-update').isDisabled());await page.locator('#ft-palettes button').filter({hasText:'Ocean Mint'}).click();assert.equal(await page.locator('#ft-param-colorA').inputValue(),'#145bff');await page.locator('#ft-apply').click();await page.waitForFunction(()=>!document.querySelector('#ft-apply').disabled);assert.equal(l.fx.numProperties,4);assert.equal(e.comp.numLayers,1);
await page.locator('#load-fx').click();await page.waitForFunction(()=>!document.querySelector('#ft-update').disabled);await page.locator('#ft-param-colorA').fill('#cc3344');await page.locator('#ft-param-animate').check();await page.locator('#ft-update').click();await page.waitForFunction(()=>!document.querySelector('#ft-update').disabled);assert.equal(e.rpc({action:'fxTools',operation:'load',id:'prism'}).params.colorA,'#cc3344');assert.equal(l.fx.numProperties,4);
await page.locator('#ft-param-duration').fill('');assert(await page.locator('#ft-update').isDisabled());await page.locator('#ft-param-duration').fill('6');await page.locator('#ft-back').click();await page.locator('.ft-card').filter({hasText:'Bloom Glow'}).getByText('Customize',{exact:true}).click();await page.locator('#ft-param-tint').check();await page.locator('#ft-param-color').fill('#2244ee');await page.locator('#ft-apply').click();await page.waitForFunction(()=>!document.querySelector('#ft-apply').disabled);assert.equal(l.fx.numProperties,8);await page.locator('#load-fx').click();await page.waitForFunction(()=>!document.querySelector('#ft-update').disabled);
for(const width of [300,380,768,1200]){await page.setViewportSize({width,height:650});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const a=await page.locator('.ft-actions').boundingBox(),f=await page.locator('footer').boundingBox();assert(a.y+a.height<=f.y+1);}
await page.setViewportSize({width:380,height:850});await page.screenshot({path:'/tmp/motionastra-fxtools.png'});l.selected=false;const other=e.comp.add('shape');other.selected=true;await page.locator('#ft-update').click();await page.waitForFunction(()=>!document.querySelector('#ft-update').disabled);assert.equal(other.fx.numProperties,0);assert((await page.locator('#notice-text').innerText()).includes('Selection changed'));other.selected=false;l.selected=true;await page.locator('#ft-remove').click();await page.waitForFunction(()=>!document.querySelector('#ft-remove').disabled);assert.equal(l.fx.numProperties,4);assert(await page.locator('#ft-apply').isVisible());
await page.locator('#ft-back').click();await page.locator('.ft-card').filter({hasText:'Glass Surface'}).getByText('Customize',{exact:true}).click();await page.locator('#ft-apply').click();await page.waitForFunction(()=>!document.querySelector('#ft-apply').disabled);assert.equal(l.fx.numProperties,9);await page.locator('#load-fx').click();await page.waitForFunction(()=>!document.querySelector('#ft-update').disabled);await page.locator('#ft-param-color').fill('#336699');await page.locator('#ft-update').click();await page.waitForFunction(()=>!document.querySelector('#ft-update').disabled);assert.equal(e.rpc({action:'fxTools',operation:'load',id:'glass'}).params.color,'#336699');await page.locator('#ft-remove').click();await page.waitForFunction(()=>!document.querySelector('#ft-remove').disabled);assert.equal(l.fx.numProperties,4);
await page.locator('[data-tab="Settings"]').first().click();await page.locator('#diagnose').click();await page.waitForFunction(()=>document.querySelector('#diagnostic-report').value.includes('nativeEffects'));assert(await page.locator('#diagnostic-report').isVisible());
const offline=await browser.newPage();await offline.goto(require('node:url').pathToFileURL(path.resolve(__dirname,'../catalog.html')).href);await offline.locator('[data-tab="FXTools"]').click();await offline.locator('.ft-card').first().getByText('Customize',{exact:true}).click();assert(await offline.locator('#ft-apply').isDisabled());assert.deepEqual(errors,[]);await browser.close();console.log('PASS: FXTools cards, palettes/parameters, Apply/Load/Update/Remove, stacking, invalid input, selection guard, responsive footer and offline preview.');})().catch(e=>{console.error(e);process.exit(1);});
