const assert=require('node:assert/strict'),{create,property}=require('./host-model.cjs');
function fixture(values=[0,100,300,400],times=[0,1,3,4]){
 const e=create(),l=e.comp.add('text'),p=property('Opacity',values[0]);l.selected=true;l.selectedProperties=[p];p.selectedKeys=[2,3];p.keys=values;p.keyTimes=times;p.numKeys=values.length;p.state=values.map(()=>({inType:1,outType:1,inEase:[{speed:7,influence:20}],outEase:[{speed:9,influence:30}],auto:false,continuous:false}));
 p.keyInInterpolationType=k=>p.state[k-1].inType;p.keyOutInterpolationType=k=>p.state[k-1].outType;p.keyInTemporalEase=k=>p.state[k-1].inEase;p.keyOutTemporalEase=k=>p.state[k-1].outEase;p.keyTemporalAutoBezier=k=>p.state[k-1].auto;p.keyTemporalContinuous=k=>p.state[k-1].continuous;
 p.setTemporalAutoBezierAtKey=(k,v)=>p.state[k-1].auto=v;p.setTemporalContinuousAtKey=(k,v)=>p.state[k-1].continuous=v;p.setInterpolationTypeAtKey=(k,a,b)=>Object.assign(p.state[k-1],{inType:a,outType:b});p.setTemporalEaseAtKey=(k,a,b)=>Object.assign(p.state[k-1],{inEase:Array.from(a,x=>({...x})),outEase:Array.from(b,x=>({...x}))});
 p.keyRoving=()=>false;p.keyOutSpatialTangent=p.keyInSpatialTangent=()=>[0,0];return {e,l,p};
}
const apply=(e,curve=[.25,.1,.75,.9])=>e.rpc({action:'tool',name:'curve',curve});
{const {e,p}=fixture(),before=JSON.parse(JSON.stringify(p.state)),keys=JSON.stringify(p.keys),times=JSON.stringify(p.keyTimes);assert.equal(apply(e).changed,1);assert.equal(p.state[1].outEase[0].influence,25);assert.equal(p.state[1].outEase[0].speed,40);assert(Math.abs(p.state[2].inEase[0].speed-40)<1e-9);assert.deepEqual(p.state[1].inEase,before[1].inEase);assert.deepEqual(p.state[2].outEase,before[2].outEase);assert.deepEqual(p.state[0],before[0]);assert.deepEqual(p.state[3],before[3]);assert.equal(JSON.stringify(p.keys),keys);assert.equal(JSON.stringify(p.keyTimes),times);}
{const {e,p}=fixture([300,100,-100],[0,1,2]);p.selectedKeys=[1,2,3];assert.equal(apply(e).changed,2);assert(Math.abs(p.state[1].inEase[0].speed+80)<1e-9);assert.equal(p.state[1].outEase[0].speed,-80);}
{const {e,p}=fixture([[0,100],[100,50]],[0,2]);p.selectedKeys=[1,2];assert.equal(apply(e).changed,1);assert.deepEqual(p.state[0].outEase.map(x=>x.speed),[20,-10]);}
{const {e,p}=fixture([[0,0],[60,80]],[0,2]);p.selectedKeys=[1,2];p.isSpatial=true;assert.equal(apply(e).changed,1);assert.equal(p.state[0].outEase.length,1);assert.equal(p.state[0].outEase[0].speed,20);p.keyOutSpatialTangent=()=>[10,0];assert.equal(apply(e).changed,0);assert.equal(apply(e,[.6,0,.8,1]).changed,1);p.keyRoving=()=>true;assert.equal(apply(e).changed,0);}
for(const mode of ['locked','expression','gap','one','shape','invalid']){const {e,l,p}=fixture(),before=JSON.stringify(p.state);if(mode==='locked')l.locked=true;if(mode==='expression')p.expression='value';if(mode==='gap')p.selectedKeys=[1,3];if(mode==='one')p.selectedKeys=[1];if(mode==='shape')p.keys=[{}, {}, {}, {}];const r=apply(e,mode==='invalid'?[.9,0,.2,1]:undefined);assert(!r.changed,mode);assert.equal(JSON.stringify(p.state),before,mode);}
{const {e,p}=fixture(),before=JSON.stringify(p.state),set=p.setTemporalEaseAtKey;let calls=0;p.setTemporalEaseAtKey=(...a)=>{if(++calls===2)throw Error('Injected native failure');return set(...a);};const r=apply(e);assert.equal(r.changed,0);assert(r.message.includes('restored'));assert.equal(JSON.stringify(p.state),before);}
console.log('PASS: Bezier-to-native speeds/influences, descending/multidimensional/spatial properties, adjacent intervals, outside handles/times/values preserved, validation and native-failure rollback.');
