const assert=require('node:assert/strict'),{create}=require('./host-model.cjs');
const e=create(),l=e.comp.add('text');l.selected=true;
let r=e.rpc({action:'apply',id:'counter',params:{},smart:true});
assert.equal(r.changed,1);assert(r.selection,'Mutation returns selection snapshot');
const target=r.selection.layers[0].core.target;
assert.equal(e.rpc({action:'load',target}).ok,true);
l.selected=false;const other=e.comp.add('text');other.selected=true;e.rpc({action:'apply',id:'counter',params:{},smart:true});
assert.equal(e.rpc({action:'load',target}).ok,false,'A follow-up load must reject another selected layer');
console.log('PASS: post-Apply snapshot and selection-bound reload');
const opts={duration:1,stagger:.04,intensity:100,seed:7,group:'chars',order:'forward',easing:'preset',placement:'edges'};
const y=create(),t=y.comp.add('text');t.selected=true;
y.rpc({action:'yuText',operation:'apply',id:1,options:{...opts,mode:'BOTH'}});
y.rpc({action:'yuText',operation:'apply',id:2,options:{...opts,mode:'OUT'}});
const incoming=y.rpc({action:'yuText',operation:'load',phase:'IN'});
assert.equal(incoming.options.mode,'IN','Loading IN must not overwrite independent OUT');
const missing=create(),mt=missing.comp.add('text');mt.selected=true;missing.rpc({action:'yuText',operation:'apply',id:1,options:{...opts,mode:'IN'}});
assert.equal(missing.rpc({action:'yuText',operation:'load',phase:'OUT'}).ok,false,'Explicit missing phase must not fall back');
l.selected=true;other.selected=false;
const baseline=e.rpc({action:'load'});assert.equal(typeof baseline.revision,'string');
e.rpc({action:'update',id:'counter',params:{end:900},target:baseline.target});
const stale=e.rpc({action:'update',id:'counter',params:{end:500},target:baseline.target,revision:baseline.revision});
assert.equal(stale.changed||0,0,'Same-token external edits require reload');
assert.equal(e.rpc({action:'load'}).params.end,900);
