const assert=require('node:assert/strict');const {create,property}=require('./host-model.cjs');
const near=(a,b)=>{assert.equal(a.length,b.length);a.forEach((v,i)=>assert(Math.abs(v-b[i])<1e-7,`${a} != ${b}`));};
for(const kind of ['text','shape','video','solid','still'])for(let i=0;i<9;i++){const e=create(),l=e.comp.add(kind);l.selected=true;l.transform.property('ADBE Position').value=[400,220];l.transform.property('ADBE Scale').value=[-150,80];l.transform.property('ADBE Rotate Z').value=35;const x=i%3/2,y=Math.floor(i/3)/2,dx=320*x*-1.5,dy=180*y*.8,r=35*Math.PI/180;
 const result=e.rpc({action:'tool',name:'anchor',x,y,keep:true});assert.equal(result.changed,1,result.message);near(l.transform.property('ADBE Anchor Point').value,[320*x,180*y]);near(l.transform.property('ADBE Position').value,[400+dx*Math.cos(r)-dy*Math.sin(r),220+dx*Math.sin(r)+dy*Math.cos(r)]);assert.equal(l.fx.numProperties,0,'Probe must be removed');}
// Native 3D probe output includes orientation and parenting; tool consumes it without 2D assumptions.
{const e=create(),l=e.comp.add('shape');l.selected=true;l.threeDLayer=true;l.parent=e.comp.add('video');l.probeBasis=[[0,0,1],[0,1,0],[-2,0,0]];l.transform.property('ADBE Anchor Point').value=[0,0,10];l.transform.property('ADBE Position').value=[20,30,40];const r=e.rpc({action:'tool',name:'anchor',x:1,y:1,keep:true});assert.equal(r.changed,1,r.message);near(l.transform.property('ADBE Anchor Point').value,[320,180,10]);near(l.transform.property('ADBE Position').value,[20,210,-600]);}
// Separated Position and animated anchor/position retain key counts and offsets.
{const e=create(),l=e.comp.add('text');l.selected=true;const ap=l.transform.property('ADBE Anchor Point'),pos=l.transform.property('ADBE Position');ap.value=[10,5];ap.numKeys=2;ap.keys=[[0,0],[20,10]];const x=property('X',100),y=property('Y',50);x.numKeys=2;x.keys=[90,110];pos.dimensionsSeparated=true;pos.getSeparationFollower=i=>i===0?x:y;
const r=e.rpc({action:'tool',name:'anchor',x:.5,y:.5,keep:true});assert.equal(r.changed,1,r.message);near(ap.keys[0],[150,85]);near(ap.keys[1],[170,95]);assert.deepEqual(x.keys,[240,260]);assert.equal(y.value,135);assert.equal(ap.numKeys,2);}
// Expressions are wrapped with their original source, not discarded; repeat offset merges delta.
{const e=create(),l=e.comp.add('video');l.selected=true;const p=l.transform.property('ADBE Position');p.expression='value + [20,30]';e.rpc({action:'tool',name:'offset',x:10,y:-5,z:0});e.rpc({action:'tool',name:'offset',x:3,y:2,z:0});const record=JSON.parse(decodeURIComponent(p.expression.split('\n')[0].slice(14)));assert.equal(record.base,'value + [20,30]');assert.deepEqual(record.delta,[13,-3]);}
// Unsupported/locked layers do not prevent the remaining selection from being handled.
{const e=create(),l=e.comp.add('text'),camera=e.comp.add('video'),locked=e.comp.add('video');[l,camera,locked].forEach(l=>l.selected=true);camera.transform.items=camera.transform.items.filter(p=>p.name!=='ADBE Anchor Point');locked.locked=true;const r=e.rpc({action:'tool',name:'anchor',x:.5,y:.5,keep:false});assert.equal(r.changed,1);assert.equal(r.severity,'warning');assert.equal(e.rpc({action:'tool',name:'unlock'}).changed,3);}
for(const [mode,expected] of [['top','BDA C'.replace(/ /g,'')],['bottom','ACBD'],['up','BADC'],['down','ACBD'],['reverse','ADCB'],['name','ADCB']]){const e=create();const ls='ABCD'.split('').map(name=>{const l=e.comp.add('text');l.name=name;return l;});ls[1].selected=ls[3].selected=true;if(mode==='name'){ls[1].name='Z';ls[3].name='B';}const r=e.rpc({action:'tool',name:'arrange',mode});assert(r.ok,r.message);const order=e.comp.items.map(l=>'ABCD'[ls.indexOf(l)]).join('');assert.equal(order,expected,mode);}
{const e=create(),a=e.comp.add('text'),b=e.comp.add('text');a.selected=b.selected=true;b.inPoint=3;const r=e.rpc({action:'tool',name:'stagger',seconds:.2});assert.equal(r.changed,2);assert(Math.abs(b.startTime-(-1.3))<1e-8);assert.equal(e.rpc({action:'tool',name:'rename',prefix:'Title'}).changed,2);assert.equal(a.name,'Title 01');const p=property('Opacity',100);p.selectedKeys=[1,2];a.selectedProperties=[p];assert.equal(e.rpc({action:'tool',name:'ease',mode:'both',strength:75}).changed,2);assert.equal(e.rpc({action:'tool',name:'style',size:72,color:'#ff8800',align:'center'}).changed,2);assert.equal(a.text.property('ADBE Text Document').value.fontSize,72);assert.equal(e.rpc({action:'tool',name:'parent'}).changed,2);assert(a.parent&&a.parent===b.parent);assert.equal(e.rpc({action:'tool',name:'unparent'}).changed,2);assert.equal(a.parent,null);}
console.log('PASS: 9-point anchors on five source types; negative scale/rotation; parented 3D probe pipeline; separated and keyed positions; expression-offset preservation; mixed locked/camera selection; all six ordering modes; stagger/rename/ease/style/parent/unparent.');

// Creation tools work without a selection, select only their result, and use CTI timing.
for(const kind of ['newShape','newSolid','newText']){const e=create(),old=e.comp.add('video');old.selected=true;let received=null;const add=e.comp.layers.addSolid;e.comp.layers.addSolid=(...args)=>{received=args;return add(...args);};const r=e.rpc({action:'tool',name:kind,color:'#e67322'});assert.equal(r.changed,1,r.message);assert.equal(e.comp.numLayers,2);assert.equal(e.comp.selectedLayers.length,1);const l=e.comp.selectedLayers[0];assert.notEqual(l,old);assert.equal(l.inPoint,e.comp.time);assert.equal(l.outPoint,e.comp.duration);if(kind==='newShape'){const c=l.vectors.property(1).property('ADBE Vectors Group');assert.equal(c.property('ADBE Vector Shape - Group').property('ADBE Vector Shape').value.vertices.length,4);near(c.property('ADBE Vector Graphic - Fill').property('ADBE Vector Fill Color').value,[230/255,115/255,34/255,1]);}if(kind==='newSolid'){near(received[0],[230/255,115/255,34/255]);assert.equal(received[2],e.comp.width);assert.equal(received[3],e.comp.height);}}
{const e=create();const before=e.comp.numLayers;const r=e.rpc({action:'tool',name:'newSolid',color:'not-a-color'});assert.equal(r.ok,false);assert.equal(e.comp.numLayers,before);}
console.log('PASS creation: shape geometry/fill, solid color/dimensions, text, CTI timing, selection and invalid-color guard.');
