const assert=require('node:assert/strict'),{setup,animated,clone}=require('./transform-motion-fixture.cjs');
const names=['ADBE Anchor Point','ADBE Position','ADBE Scale','ADBE Rotate Z','ADBE Opacity'];
const copy=e=>e.rpc({action:'copyMotion'}),paste=(e,motion)=>e.rpc({action:'pasteMotion',motion});
function source(e,name='ADBE Position',frames=[20,32,44]){const l=e.layer();l.selected=true;const p=l.transform.property(name),v=Array.isArray(p.value)?[[5,10],[20,30],[40,50]]:[10,25,70];animated(p,frames.map(f=>f/30),v,p.isSpatial);return {l,p};}
// These assertions fail if Copy is absent, creates undo steps, or writes its source.
{const e=setup();assert.match(copy(e).message,/select exactly one/i);const a=e.layer(),b=e.layer();a.selected=b.selected=true;assert.match(copy(e).message,/exactly one/i);b.selected=false;assert.match(copy(e).message,/no supported transform keyframes/i);assert.equal(e.undo.length,0);}
for(const name of names){const e=setup(),{p}=source(e,name),before=p.rows(),r=copy(e);assert(r.ok,r.message);assert.equal(e.undo.length,0);assert.deepEqual(p.rows(),before);assert.equal(r.motion.properties.length,1);assert.deepEqual(r.motion.properties[0].keys.map(k=>Math.round(k.time*30)),[0,12,24]);const target=e.layer('shape');e.comp.items.forEach(l=>l.selected=false);target.selected=true;e.comp.time=100/30;const done=paste(e,r.motion);assert.equal(done.changed,1,done.message);assert.deepEqual(target.transform.property(name).rows().map(k=>Math.round(k.time*30)),[100,112,124]);assert.equal(e.undo.at(-1),'Paste ZxT Motion');assert.equal(e.ends,1);}
{const e=setup(),{l,p}=source(e);p.configure(1,{inType:1,outType:1});p.configure(2,{auto:true,continuous:true,sAuto:true,sContinuous:true,sIn:[-10,-5],sOut:[15,9],roving:true});p.configure(3,{inType:3,outType:3});p.expression='value+[3,3]';const c=copy(e);assert(!JSON.stringify(c.motion).includes('value+'));const t1=e.layer('shape'),t2=e.layer('solid');l.selected=false;t1.selected=t2.selected=true;e.comp.time=2;const result=paste(e,c.motion);assert.equal(result.changed,2);assert.equal(e.undo.length,1);for(const t of [t1,t2]){const r=t.transform.property('ADBE Position').rows(),old=p.rows();for(let i=0;i<3;i++){const {time,...a}=r[i],{time:original,...b}=old[i];assert.deepEqual(a,b);}assert.deepEqual(r.map(x=>Math.round(x.time*30)),[60,72,84]);}}
// Shared origin across properties; no expressions, effects or other data are copied.
{const e=setup(),{l}=source(e);animated(l.transform.property('ADBE Opacity'),[10/30,22/30],[20,80]);l.fx.addProperty('Unrelated');l.masks.addProperty('ADBE Mask Atom');const r=copy(e);assert.equal(r.motion.properties.length,2);assert.equal(r.motion.properties.find(p=>p.matchName==='ADBE Position').keys[0].time,10/30);assert.equal(r.motion.properties.find(p=>p.matchName==='ADBE Opacity').keys[0].time,0);
 l.selected=false;const t=e.layer('shape');t.selected=true;t.comment='Keep';t.parent=l;t.inPoint=-2;t.outPoint=50;t.startTime=-3;t.fx.addProperty('Keep effect');t.masks.addProperty('ADBE Mask Atom');t.vectors.addProperty('ADBE Vector Group');t.transform.property('ADBE Rotate Z').expression='time*20';const before={fx:t.fx.items.length,masks:t.masks.items.length,vectors:t.vectors.items.length,parent:t.parent,inPoint:t.inPoint,outPoint:t.outPoint,startTime:t.startTime,comment:t.comment,expression:t.transform.property('ADBE Rotate Z').expression};
 assert.equal(paste(e,r.motion).changed,1);assert.deepEqual({fx:t.fx.items.length,masks:t.masks.items.length,vectors:t.vectors.items.length,parent:t.parent,inPoint:t.inPoint,outPoint:t.outPoint,startTime:t.startTime,comment:t.comment,expression:t.transform.property('ADBE Rotate Z').expression},before);}
{const e=setup(),{l}=source(e),c=copy(e).motion;l.selected=false;assert.match(paste(e,null).message,/copy motion/i);assert.match(paste(e,c).message,/select at least one/i);const t=e.layer();t.selected=true;const p=t.transform.property('ADBE Position');animated(p,[100/30,112/30],[[1,2],[3,4]],true);const old=p.rows();e.comp.time=100/30;assert.equal(paste(e,c).changed,0);assert.deepEqual(p.rows(),old);e.comp.time=-1;assert.equal(paste(e,c).changed,0,'Conservative policy also preserves non-overlapping existing animation');assert.deepEqual(p.rows(),old);}
for(const mode of ['locked','expression','disabled-expression','dimensions','unwritable','separated','missing']){const e=setup(),{l}=source(e),m=copy(e).motion;l.selected=false;const t=e.layer('solid');t.selected=true;const p=t.transform.property('ADBE Position');if(mode==='locked')t.locked=true;if(/expression/.test(mode)){p.expression='value';p.expressionEnabled=mode!=='disabled-expression';}if(mode==='dimensions')p.value=[0,0,0];if(mode==='unwritable')p.canVaryOverTime=false;if(mode==='separated')p.dimensionsSeparated=true;if(mode==='missing')t.transform.items=t.transform.items.filter(x=>x!==p);assert.equal(paste(e,m).changed,0,mode);assert.equal(p.numKeys,0);}
{const e=setup(),{l}=source(e);animated(l.transform.property('ADBE Opacity'),[1,2],[10,80]);const m=copy(e).motion;l.selected=false;const t=e.layer();t.selected=true;t.transform.property('ADBE Position').expression='value';assert.equal(paste(e,m).changed,1);assert.equal(t.transform.property('ADBE Position').numKeys,0);assert.equal(t.transform.property('ADBE Opacity').numKeys,2);}
// Native failures roll back only the affected, previously unanimated property.
for(const failure of ['values','attributes','roving-retime']){const e=setup(),{l,p}=source(e);p.configure(2,{roving:true});const m=copy(e).motion;l.selected=false;const t=e.layer();t.selected=true;const q=t.transform.property('ADBE Position'),original=clone(q.value);if(failure==='values'){const set=q.setValueAtTime;let n=0;q.setValueAtTime=(...a)=>{if(++n===2)throw Error('Native failure');set(...a);};}if(failure==='attributes')q.setSpatialTangentsAtKey=()=>{throw Error('Native attributes failure');};if(failure==='roving-retime'){q.setRovingAtKey=(i,v)=>{if(v)q.keyTime=n=>m.properties[0].keys[n-1].time+e.comp.time+0.1;};}const r=paste(e,m);assert.equal(r.changed,0,r.message);assert.equal(q.numKeys,0);assert.deepEqual(q.value,original);assert.match(r.message,/restored/i);assert.equal(e.ends,1);}
// Separated Position copies/pastes its axes only when representation matches.
{const e=setup(),l=e.layer();l.selected=true;const leader=l.transform.property('ADBE Position');const axes=[animated({name:'X',matchName:'ADBE Position_0',value:0},[1,2],[5,15]),animated({name:'Y',matchName:'ADBE Position_1',value:0},[1.5,2.5],[10,25])];leader.dimensionsSeparated=true;leader.getSeparationFollower=i=>axes[i];const m=copy(e).motion;assert.equal(m.properties.length,2);l.selected=false;const t=e.layer();t.selected=true;const to=[animated({name:'X',value:0}),animated({name:'Y',value:0})];const target=t.transform.property('ADBE Position');target.dimensionsSeparated=true;target.getSeparationFollower=i=>to[i];e.comp.time=5;assert.equal(paste(e,m).changed,1);assert.deepEqual(to[0].rows().map(x=>x.time),[5,6]);assert.deepEqual(to[1].rows().map(x=>x.time),[5.5,6.5]);}
{const e=setup(),{l}=source(e),m=copy(e).motion;l.selected=false;const t=e.layer();t.selected=true;const bad=clone(m);bad.properties[0].matchName='ADBE Effect Parade';assert.equal(paste(e,bad).ok,false);assert.equal(t.fx.items.length,0);assert.equal(t.transform.property('ADBE Position').numKeys,0);}
// All five animated Transforms share one global origin; 3D values stay 3D.
{const e=setup(),l=e.layer('solid');l.selected=true;l.threeDLayer=true;names.forEach((name,i)=>{const p=l.transform.property(name);if(Array.isArray(p.value))p.value=[0,0,0];animated(p,[i/30,(i+12)/30],Array.isArray(p.value)?[[i,10,20],[i+10,30,40]]:[i,50],p.isSpatial);});const m=copy(e).motion;assert.equal(m.properties.length,5);l.selected=false;const t=e.layer('text');t.selected=true;t.threeDLayer=true;t.transform.items.forEach(p=>{if(Array.isArray(p.value))p.value=[0,0,0];});const doc=JSON.stringify(t.text.property('ADBE Text Document').value);t.text.property('ADBE Text Animators').addProperty('ADBE Text Animator');const anim=t.text.property('ADBE Text Animators').items[0];assert.equal(paste(e,m).changed,1);assert.equal(t.text.property('ADBE Text Animators').items[0],anim);assert.equal(JSON.stringify(t.text.property('ADBE Text Document').value),doc);}
{const e=setup(),{l}=source(e);l.locked=true;assert(copy(e).ok,'Copy is read-only, so a locked source is readable');e.project.activeItem=null;assert.equal(copy(e).ok,false);assert.equal(e.undo.length,0);}
// Incompatible reads and malformed clipboards never write a target.
{const e=setup(),{l,p}=source(e);p.keyInTemporalEase=()=>{throw Error('Unreadable metadata');};assert.equal(copy(e).ok,false);assert.equal(e.undo.length,0);}
{const e=setup(),{l}=source(e),m=copy(e).motion;l.selected=false;const t=e.layer();t.selected=true;for(const damage of [x=>x.properties[0].keys[0].time=-1,x=>x.properties[0].keys[1].time=0,x=>x.properties[0].keys[0].inEase=[],x=>x.properties[0].keys[0].value=[0,0,0],x=>x.properties[0].keys[0].roving=true]){const bad=clone(m);damage(bad);assert.equal(paste(e,bad).ok,false);assert.equal(t.transform.property('ADBE Position').numKeys,0);}}
for(const rollbackFailed of [false,true]){const e=setup(),{l}=source(e),m=copy(e).motion;l.selected=false;const t=e.layer();t.selected=true;const p=t.transform.property('ADBE Position');if(rollbackFailed){p.setTemporalEaseAtKey=()=>{throw Error('Native failure');};p.removeKey=()=>{throw Error('Rollback failure');};}e.context.app.endUndoGroup=()=>{throw Error('Undo close failure');};const r=paste(e,m);assert(r.recovery,'Undo-close failure must retain recovery even after failed rollback');assert.equal(r.severity,'warning');assert.equal(p.numKeys,3);assert.equal(r.changed,rollbackFailed?0:1);}
console.log('PASS: Transform-only copy, shared relative timing, CTI 100/112/124, multi-target, interpolation/ease/spatial/roving preservation, conservative conflicts, protected data and per-property rollback.');
