const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright');
const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');const {create}=require('./host-model.cjs');const root=path.resolve(__dirname,'..'),data=JSON.parse(fs.readFileSync(path.join(root,'presets.json')));
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||undefined,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1200,height:850}}),errors=[],env=create();env.comp.add('text').selected=true;env.context.app.fonts={allFonts:[[{postScriptName:'Inter-Regular',familyName:'Inter',styleName:'Regular'}]]};
page.on('pageerror',e=>errors.push(e.message));await page.exposeFunction('hostRpc',p=>env.rpc(p));await page.addInitScript(()=>{const bridge={isAvailable:()=>true,isReady:()=>true,call:async p=>{const r=await window.hostRpc(p);if(!r.ok)throw Error(r.message);if(p.action!=='status')window.lastReply=r;return r;}};Object.defineProperty(window,'MotionAstraBridge',{get:()=>bridge,set(){}});});
await page.goto(require('node:url').pathToFileURL(path.join(root,'index.html')).href);assert.equal(await page.locator('.category-tabs button').allTextContents().then(a=>a.map(s=>s.trim()).join('|')),'Library|Motion|Create');await page.locator('#fold-quick').click();await page.locator('[data-workspace="Motion"]').click();await page.locator('[data-tab="Tools"]').click();assert(await page.locator('#anchor-grid').isVisible());assert(await page.locator('#search').isHidden());await page.locator('#fold-quick').click();await page.locator('[data-workspace="Library"]').click();await page.locator('[data-tab="YU"]').click();assert.equal(await page.locator('.card').count(),6);
for(const width of [300,320,380,768,1200]){await page.setViewportSize({width,height:650});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Horizontal overflow at '+width);const tabs=await page.locator('.category-tabs button').evaluateAll(a=>a.map(e=>({y:e.getBoundingClientRect().y,w:e.clientWidth,scroll:e.scrollWidth,h:e.getBoundingClientRect().height})));assert(tabs.every(t=>Math.abs(t.y-tabs[0].y)<1),'Menu wrapped at '+width);assert(tabs.every(t=>t.scroll<=t.w&&t.h>=28),'Menu label clipped or target too small at '+width);const work=await page.locator('#workspace').boundingBox(),foot=await page.locator('footer').boundingBox();assert(work.y+work.height<=foot.y+1);}
await page.setViewportSize({width:320,height:650});const original=await page.locator('#workspace').boundingBox();await page.locator('#fold-nav').click();await page.locator('#fold-quick').click();const folded=await page.locator('#workspace').boundingBox();assert(folded.height>original.height+50);await page.reload();assert.equal(await page.locator('#fold-nav').getAttribute('aria-expanded'),'false');await page.locator('#fold-nav').click();await page.locator('#fold-quick').click();
for(const r of data.presets){await page.locator(`[data-tab="${r.category==='Text'?'YU':r.category}"]`).click();assert.equal(await page.locator('.card').count(),r.category==='Text'?6:8);await page.locator('.card').filter({hasText:r.name}).locator('.customize').click();env.comp.items.forEach(l=>l.selected=false);if(r.category==='Text')env.comp.add('text').selected=true;
if(r.category==='Background'){assert.equal(await page.locator('#param-duration').getAttribute('type'),'number');assert.equal(await page.locator('#exact-duration').count(),0);await page.locator('#param-static').check();}assert.equal(await page.locator('#param-loop').count(),0);assert.equal(await page.locator('#param-loopMode option').allTextContents().then(a=>a.join('|')),'Ping-Pong|Cycle|Continue|None');await page.locator('#param-loopMode').selectOption('0');await page.locator('#apply').click();await page.waitForFunction(()=>!document.querySelector('#update').hidden);await page.waitForFunction(()=>!document.querySelector('#update').hidden && !document.querySelector('#quick-anchor').disabled);assert.equal(env.rpc({action:'load'}).id,r.id);assert.equal(env.rpc({action:'load'}).params.loopMode,0);
await page.locator('#param-manual').check();await page.locator('#exact-progress').fill('40');await page.locator('#update').click();await page.waitForFunction(()=>!document.querySelector('#quick-anchor').disabled);assert.equal(env.rpc({action:'load'}).params.progress,40);
assert(await page.locator('#apply').isHidden(),'Applied instance has one primary Update action');assert.equal(await page.locator('#inspector-load').count(),0);assert.equal(await page.locator('#quick #load-fx').count(),1);const actions=await page.locator('#inspector .inspector-actions').boundingBox(),footer=await page.locator('footer').boundingBox();assert(actions.y+actions.height<=footer.y+1,'Actions overlap status');await page.locator('#close').click();}
// Customized colors survive returning to the card; repeat Generate updates one layer.
await page.locator('[data-workspace="Library"]').click();await page.locator('[data-tab="Background"]').click();await page.locator('.card').filter({hasText:'Neon Grid'}).locator('.customize').click();await page.locator('#param-color2').fill('#ee2244');await page.locator('#close').click();env.comp.items.forEach(l=>l.selected=false);const beforeGenerate=env.comp.numLayers;await page.locator('.card').filter({hasText:'Neon Grid'}).locator('.customize').click();await page.locator('#apply').click();await page.waitForFunction(()=>!document.querySelector('#update').hidden && !document.querySelector('#quick-anchor').disabled);assert.equal(env.comp.numLayers,beforeGenerate+1);assert.equal(env.rpc({action:'load'}).params.color2,'#ee2244');await page.locator('#param-color2').fill('#ee2244');await page.locator('#update').click();await page.waitForFunction(()=>!document.querySelector('#update').hidden && !document.querySelector('#quick-anchor').disabled);assert.equal(env.comp.numLayers,beforeGenerate+1);
// Precise counter fields, switcher text and native-control settings roundtrip.
await page.locator('[data-workspace="Library"]').click();await page.locator('[data-tab="YU"]').click();env.comp.items.forEach(l=>l.selected=false);env.comp.add('text').selected=true;await page.locator('.card').filter({hasText:'Counter Text'}).locator('.customize').click();await page.fill('#param-start','-250.5');await page.fill('#param-end','2500.75');await page.locator('#param-decimals').selectOption('2');await page.fill('#param-prefix','Rp ');await page.locator('#apply').click();await page.waitForFunction(()=>!document.querySelector('#update').hidden && !document.querySelector('#quick-anchor').disabled);let loaded=env.rpc({action:'load'});assert.equal(loaded.params.start,-250.5);assert.equal(loaded.params.end,2500.75);assert.equal(loaded.params.prefix,'Rp ');
await page.fill('#param-end','');assert(await page.locator('#apply').isDisabled());await page.fill('#param-end','5000');await page.locator('#update').click();await page.waitForFunction(()=>!document.querySelector('#quick-anchor').disabled);assert.equal(env.rpc({action:'load'}).params.end,5000);
const selected=env.comp.selectedLayers[0];selected.fx.property('MA2 MotionAstra Progress').property(1).setValue(61);await page.locator('#load-fx').click();await page.waitForFunction(()=>document.querySelector('#param-progress').value==='61');
await page.setViewportSize({width:320,height:360});await page.locator('#update').scrollIntoViewIfNeeded();const shortApply=await page.locator('#update').boundingBox(),shortFooter=await page.locator('footer').boundingBox();assert(shortApply.y+shortApply.height<=shortFooter.y+1,'Apply inaccessible at short height');await page.setViewportSize({width:320,height:650});await page.locator('#fold-nav').click();await page.locator('#fold-quick').click();await page.locator('#inspector .inspector-scroll').evaluate(e=>e.scrollTop=190);await page.screenshot({path:path.join(root,'panel-narrow-preview.png')});await page.locator('#fold-nav').click();await page.locator('#fold-quick').click();
await page.locator('#close').click();await page.locator('[data-workspace="Motion"]').click();await page.locator('[data-tab="Tools"]').click();await page.locator('[aria-label="Anchor 1"]').click();await page.waitForFunction(()=>!document.querySelector('#quick-anchor').disabled);assert.deepEqual(Array.from(selected.transform.property('ADBE Anchor Point').value),[0,0]);
await page.locator('#erase-all').click();assert(await page.locator('#review').isVisible());assert(selected.fx.numProperties>0);await page.locator('#cancel-remove').click();assert(selected.fx.numProperties>0);await page.locator('#erase-all').click();await page.locator('#confirm-remove').click();await page.waitForFunction(()=>!document.querySelector('#quick-anchor').disabled);assert.equal(selected.fx.numProperties,0);
assert(await page.locator('#notice').evaluate(e=>e.classList.contains('visible')));await page.waitForTimeout(3700);assert(!await page.locator('#notice').evaluate(e=>e.classList.contains('visible')));await page.locator('#show-history').click();assert(await page.locator('#history li').count()>0);
await page.setViewportSize({width:1200,height:850});await page.locator('[data-workspace="Library"]').click();await page.locator('[data-tab="YU"]').click();await page.screenshot({path:path.join(root,'panel-preview.png')});await page.locator('[data-workspace="Library"]').click();await page.locator('[data-tab="Background"]').click();await page.screenshot({path:path.join(root,'background-preview.png')});
await page.locator('[data-workspace="Motion"]').click();await page.locator('[data-tab="Tools"]').click();await page.screenshot({path:path.join(root,'tools-preview.png')});const offline=await browser.newPage();await offline.goto(require('node:url').pathToFileURL(path.join(root,'catalog.html')).href);await offline.locator('[data-workspace="Motion"]').click();await offline.locator('[data-tab="Tools"]').click();assert(await offline.locator('#anchor-grid').isVisible());await offline.locator('[data-workspace="Library"]').click();await offline.locator('[data-tab="YU"]').click();await offline.locator('.customize').first().click();assert(await offline.locator('#apply').isDisabled());assert(await offline.locator('#update').isDisabled());assert.deepEqual(errors,[]);await browser.close();console.log('PASS: real Chromium + actual host dispatch/model; all 14 Apply/Update flows, number editing, native settings load, 5 widths, persistent collapse, pinned actions, anchor dispatch, erase confirm/cancel, notification timing/history and offline guard.');})().catch(e=>{console.error(e);process.exit(1);});
