const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright'),assert=require('node:assert/strict'),path=require('node:path'),{create}=require('./host-model.cjs');
(async()=>{const e=create(),l=e.comp.add('text');l.selected=true;const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']}),page=await browser.newPage({viewport:{width:380,height:850}}),errors=[];
page.on('pageerror',x=>errors.push(x.message));await page.exposeFunction('hostRpc',a=>e.rpc(a));await page.addInitScript(()=>{const bridge={isAvailable:()=>true,isReady:()=>true,call:async a=>{const r=await window.hostRpc(a);if(a.action!=='status')window.lastReply=r;if(!r.ok)throw Error(r.message);return r;}};Object.defineProperty(window,'MotionAstraBridge',{get:()=>bridge,set(){}});});
await page.goto(require('node:url').pathToFileURL(path.resolve(__dirname,'../index.html')).href);await page.locator('[data-workspace="Library"]').click();await page.locator('[data-tab="YU"]').click();assert.equal(await page.locator('.yu-card').count(),120);assert((await page.locator('#yu').innerText()).includes('YUGraphic'));
await page.locator('#yu-category').selectOption('Elastic');assert.equal(await page.locator('.yu-card').count(),10);await page.locator('.yu-card').filter({hasText:/rubber pop/i}).locator('.yu-customize').click();assert.equal(await page.locator('#yu-duration').inputValue(),'1');assert(await page.locator('#yu-update').isDisabled());
await page.locator('#yu-mode').selectOption('BOTH');await page.locator('#yu-duration').fill('0.75');await page.locator('#yu-intensity').fill('120');await page.locator('#yu-apply').click();await page.waitForFunction(()=>!document.querySelector('#yu-apply').disabled);assert.equal(e.rpc({action:'yuText',operation:'load'}).options.intensity,120);assert.equal(l.fx.numProperties,0);
await page.locator('#load-fx').click();await page.waitForFunction(()=>!document.querySelector('#yu-clear').disabled);await page.locator('#yu-stagger').fill('0.08');await page.locator('#yu-update').click();await page.waitForFunction(()=>!document.querySelector('#yu-clear').disabled);assert.equal(e.rpc({action:'yuText',operation:'load'}).options.stagger,.08);
await page.locator('#yu-duration').fill('');assert(await page.locator('#yu-apply').isDisabled());assert(await page.locator('#yu-update').isDisabled());await page.locator('#yu-duration').fill('0.75');
for(const width of [300,380,768,1200]){await page.setViewportSize({width,height:650});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Overflow at '+width);const action=await page.locator('.yu-actions').boundingBox(),footer=await page.locator('footer').boundingBox();assert(action.y+action.height<=footer.y+1,'YU buttons overlap notification');}
await page.setViewportSize({width:380,height:850});await page.screenshot({path:'/tmp/motionastra-yu.png'});
l.selected=false;const other=e.comp.add('text');other.selected=true;await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await page.waitForFunction(()=>document.querySelector('#yu-update').disabled);assert.equal(other.text.property('ADBE Text Animators').numProperties,0);assert(await page.locator('#yu-clear').isDisabled(),'Stale Inspector cannot remove another layer animation');assert((await page.locator('#yu-selection-guidance').innerText()).includes('Selection changed'));
other.selected=false;l.selected=true;await page.locator('#yu-clear').click();await page.waitForFunction(()=>!document.querySelector('#yu-clear').disabled);assert.equal(l.text.property('ADBE Text Animators').numProperties,0);
await page.locator('[data-workspace="Library"]').click();await page.locator('[data-tab="Background"]').click();assert(await page.locator('#yu').isHidden());assert.equal(await page.locator('#cards .card').count(),8);
const offline=await browser.newPage();await offline.goto(require('node:url').pathToFileURL(path.resolve(__dirname,'../catalog.html')).href);await offline.locator('[data-workspace="Library"]').click();await offline.locator('[data-tab="YU"]').click();await offline.locator('.yu-customize').first().click();assert(await offline.locator('#yu-apply').isDisabled());assert.equal(await offline.locator('#yu-load').count(),0);assert.deepEqual(errors,[]);await browser.close();console.log('PASS: YU 120-card library, category/search, author credit, Apply/Load/Update/Remove, validation, stale selection, responsive footer and offline guards.');})().catch(e=>{console.error(e);process.exit(1);});
