/* Generated by tools/build-yu.py. YUGraphic MIT license: vendor/yu-text-motion/LICENSE.txt */
var MotionAstraYU=(function(){
/* Yu Text Motion 1.0 beta. Original procedural presets. ES3 compatible. */
var YTMCore = (function () {
    var presets = [];
    function clamp(x, a, b) { return Math.max(a, Math.min(b, x)); }
    function hash(n, seed) { var x = Math.sin(n * 127.1 + seed * 311.7) * 43758.5453; return x - Math.floor(x); }
    function add(category, name, spec) {
        var p = {id:presets.length + 1, category:category, name:name, x:0, y:0,
            sx:100, sy:100, rotation:0, skew:0, blur:0, ease:"cubic", pattern:"plain",
            order:"forward", duration:0.65, stagger:0.035, group:"chars", wave:0};
        var k; for (k in spec) { if (spec.hasOwnProperty(k)) { p[k] = spec[k]; } }
        presets.push(p);
    }
    add("Clean", "Soft Fade", {ease:"smooth",duration:0.5});
    add("Clean", "Quick Fade", {ease:"expo",duration:0.3,stagger:0.015});
    add("Clean", "Soft Rise", {y:22,ease:"smooth"});
    add("Clean", "Soft Fall", {y:-22,ease:"smooth"});
    add("Clean", "Gentle Zoom", {sx:92,sy:92,ease:"smooth"});
    add("Clean", "Settle Down", {sx:112,sy:112,y:-10});
    add("Clean", "Word Reveal", {y:18,group:"words",stagger:0.12});
    add("Clean", "Line Reveal", {y:25,group:"lines",stagger:0.16});
    add("Clean", "Center Fade", {order:"center",ease:"smooth"});
    add("Clean", "Reverse Whisper", {x:12,order:"reverse",duration:0.8});
    add("Slide", "Slide From Left", {x:-160});
    add("Slide", "Slide From Right", {x:160});
    add("Slide", "Slide From Bottom", {y:110});
    add("Slide", "Slide From Top", {y:-110});
    add("Slide", "Diagonal Left Up", {x:-100,y:80});
    add("Slide", "Diagonal Right Up", {x:100,y:80});
    add("Slide", "Diagonal Left Down", {x:-100,y:-80});
    add("Slide", "Diagonal Right Down", {x:100,y:-80});
    add("Slide", "Fast Whip Left", {x:-300,skew:18,ease:"expo",duration:0.45});
    add("Slide", "Fast Whip Right", {x:300,skew:-18,ease:"expo",duration:0.45});
    add("Pop", "Tiny Pop", {sx:0,sy:0,ease:"back",duration:0.45});
    add("Pop", "Big Pop", {sx:180,sy:180,ease:"back",duration:0.55});
    add("Pop", "Pop Lift", {sx:20,sy:20,y:65,ease:"back"});
    add("Pop", "Pop Drop", {sx:30,sy:30,y:-65,ease:"back"});
    add("Pop", "Pop Tilt Left", {sx:0,sy:0,rotation:-35,ease:"back"});
    add("Pop", "Pop Tilt Right", {sx:0,sy:0,rotation:35,ease:"back"});
    add("Pop", "Wide Pop", {sx:0,sy:160,ease:"back"});
    add("Pop", "Tall Pop", {sx:150,sy:0,ease:"back"});
    add("Pop", "Word Punch", {sx:165,sy:165,ease:"back",group:"words",stagger:0.16});
    add("Pop", "Center Pop", {sx:0,sy:0,ease:"back",order:"center"});
    add("Bounce", "Bounce Up", {y:150,ease:"bounce"});
    add("Bounce", "Bounce Down", {y:-150,ease:"bounce"});
    add("Bounce", "Bounce From Left", {x:-140,ease:"bounce"});
    add("Bounce", "Bounce From Right", {x:140,ease:"bounce"});
    add("Bounce", "Rubber Ball", {sx:0,sy:0,ease:"bounce"});
    add("Bounce", "Heavy Drop", {y:-220,sx:130,sy:80,ease:"bounce",duration:0.9});
    add("Bounce", "Tilt Bounce", {y:110,rotation:-30,ease:"bounce"});
    add("Bounce", "Word Bounce", {y:100,ease:"bounce",group:"words",stagger:0.12});
    add("Bounce", "Center Bounce", {y:90,ease:"bounce",order:"center"});
    add("Bounce", "Scatter Bounce", {x:120,y:120,pattern:"scatter",ease:"bounce",order:"random"});
    add("Elastic", "Spring Up", {y:110,ease:"elastic",duration:1});
    add("Elastic", "Spring Down", {y:-110,ease:"elastic",duration:1});
    add("Elastic", "Spring Left", {x:-150,ease:"elastic",duration:1});
    add("Elastic", "Spring Right", {x:150,ease:"elastic",duration:1});
    add("Elastic", "Rubber Pop", {sx:0,sy:0,ease:"elastic",duration:1});
    add("Elastic", "Rubber Stretch", {sx:20,sy:160,ease:"elastic",duration:1});
    add("Elastic", "Rubber Squash", {sx:170,sy:20,ease:"elastic",duration:1});
    add("Elastic", "Spring Tilt", {rotation:-80,ease:"elastic",duration:1});
    add("Elastic", "Word Spring", {sx:0,sy:0,ease:"elastic",group:"words",stagger:0.15,duration:1});
    add("Elastic", "Elastic Scatter", {x:110,y:90,pattern:"scatter",ease:"elastic",duration:1});
    add("Rotate", "Quarter Turn Left", {rotation:-90});
    add("Rotate", "Quarter Turn Right", {rotation:90});
    add("Rotate", "Half Turn", {rotation:180,sx:30,sy:30});
    add("Rotate", "Full Spin", {rotation:360,sx:10,sy:10,duration:0.9});
    add("Rotate", "Counter Spin", {rotation:-360,sx:10,sy:10,duration:0.9});
    add("Rotate", "Swing In", {rotation:-65,y:-30,ease:"back"});
    add("Rotate", "Pendulum", {rotation:55,ease:"elastic",duration:1});
    add("Rotate", "Alternating Tilt", {rotation:60,pattern:"alternate"});
    add("Rotate", "Tumble Rise", {rotation:-180,y:120});
    add("Rotate", "Spiral Gather", {x:100,y:100,rotation:240,pattern:"spiral",duration:0.9});
    add("Blur", "Focus In", {blur:35,ease:"smooth"});
    add("Blur", "Blur Rise", {blur:24,y:60});
    add("Blur", "Blur Drop", {blur:24,y:-60});
    add("Blur", "Blur Left", {blur:28,x:-110});
    add("Blur", "Blur Right", {blur:28,x:110});
    add("Blur", "Dream Zoom", {blur:40,sx:145,sy:145,duration:1});
    add("Blur", "Soft Bloom", {blur:20,sx:60,sy:60,duration:0.8});
    add("Blur", "Random Focus", {blur:35,order:"random"});
    add("Blur", "Center Focus", {blur:30,order:"center"});
    add("Blur", "Word Focus", {blur:24,y:12,group:"words",stagger:0.16});
    add("Typewriter", "Classic Type", {ease:"step",duration:0.06,stagger:0.075});
    add("Typewriter", "Fast Type", {ease:"step",duration:0.04,stagger:0.035});
    add("Typewriter", "Reverse Type", {ease:"step",duration:0.06,stagger:0.075,order:"reverse"});
    add("Typewriter", "Random Type", {ease:"step",duration:0.06,stagger:0.055,order:"random"});
    add("Typewriter", "Center Type", {ease:"step",duration:0.06,stagger:0.06,order:"center"});
    add("Typewriter", "Word Cut", {ease:"step",duration:0.06,stagger:0.22,group:"words"});
    add("Typewriter", "Line Cut", {ease:"step",duration:0.06,stagger:0.26,group:"lines"});
    add("Typewriter", "Keycap Pop", {sx:60,sy:60,ease:"back",duration:0.22,stagger:0.075});
    add("Typewriter", "Soft Keys", {y:14,duration:0.2,stagger:0.075});
    add("Typewriter", "Digital Steps", {y:35,ease:"steps",duration:0.35,stagger:0.055});
    add("Glitch", "Signal Jitter", {x:36,y:10,pattern:"glitch",duration:0.55});
    add("Glitch", "Vertical Signal", {x:8,y:50,pattern:"glitch",duration:0.55});
    add("Glitch", "Wide Signal", {x:85,y:3,pattern:"glitch",duration:0.55});
    add("Glitch", "Broken Zoom", {sx:145,sy:65,x:20,pattern:"glitch"});
    add("Glitch", "Skew Signal", {x:35,skew:30,pattern:"glitch"});
    add("Glitch", "Flicker Reveal", {pattern:"flicker",duration:0.6});
    add("Glitch", "Flicker Focus", {pattern:"flicker",blur:20,duration:0.7});
    add("Glitch", "Scrambled Entry", {x:65,y:35,rotation:25,pattern:"glitch",order:"random"});
    add("Glitch", "Word Interference", {x:45,y:6,pattern:"glitch",group:"words",stagger:0.13});
    add("Glitch", "Stutter Shift", {x:-90,ease:"steps",duration:0.5});
    add("Split", "Alternating Vertical", {y:100,pattern:"alternate"});
    add("Split", "Alternating Horizontal", {x:100,pattern:"alternate"});
    add("Split", "Alternating Diagonal", {x:85,y:65,pattern:"alternate"});
    add("Split", "Center Gather", {x:140,pattern:"converge",order:"center"});
    add("Split", "Edge Gather", {x:140,pattern:"converge",order:"edges"});
    add("Split", "Fan In", {x:130,y:85,rotation:45,pattern:"fan"});
    add("Split", "Scattered Letters", {x:170,y:100,rotation:55,pattern:"scatter",order:"random"});
    add("Split", "Split Bounce", {y:100,pattern:"alternate",ease:"bounce"});
    add("Split", "Split Spring", {x:110,pattern:"alternate",ease:"elastic",duration:1});
    add("Split", "Gather Pop", {x:110,sx:0,sy:0,pattern:"converge",ease:"back",order:"center"});
    add("Wave", "Ocean Rise", {y:65,wave:36,pattern:"wave",duration:0.9});
    add("Wave", "Ocean Fall", {y:-65,wave:36,pattern:"wave",duration:0.9});
    add("Wave", "Side Wave", {x:-90,wave:40,pattern:"wave",duration:0.9});
    add("Wave", "Ripple Pop", {sx:30,sy:30,wave:25,pattern:"wave",order:"center",duration:0.9});
    add("Wave", "Sine Sway", {rotation:20,wave:55,pattern:"wave",duration:1});
    add("Wave", "Arc From Left", {x:-150,wave:80,pattern:"arc",duration:0.8});
    add("Wave", "Arc From Right", {x:150,wave:80,pattern:"arc",duration:0.8});
    add("Wave", "Under Arc", {x:-120,wave:-75,pattern:"arc",duration:0.8});
    add("Wave", "Zigzag Rise", {y:90,wave:40,pattern:"zigzag",duration:0.85});
    add("Wave", "Word Wave", {y:40,wave:26,pattern:"wave",group:"words",stagger:0.15,duration:0.9});
    add("Kinetic", "Squash Release", {sx:155,sy:10,y:30,ease:"back"});
    add("Kinetic", "Stretch Release", {sx:10,sy:165,y:-30,ease:"back"});
    add("Kinetic", "Slanted Rush", {x:-190,skew:38,sx:140,ease:"expo"});
    add("Kinetic", "Reverse Rush", {x:190,skew:-38,sx:140,ease:"expo",order:"reverse"});
    add("Kinetic", "Impact Stamp", {sx:230,sy:230,rotation:-12,ease:"quint",duration:0.45,stagger:0.025});
    add("Kinetic", "Spring Stamp", {sx:200,sy:200,rotation:12,ease:"elastic",duration:1});
    add("Kinetic", "Word Slam", {y:-170,sx:140,sy:140,ease:"back",group:"words",stagger:0.16});
    add("Kinetic", "Line Sweep", {x:-180,skew:12,group:"lines",stagger:0.18});
    add("Kinetic", "Spiral Pop", {x:90,y:90,sx:0,sy:0,rotation:180,pattern:"spiral",duration:0.9});
    add("Kinetic", "Scatter Snap", {x:160,y:110,sx:40,sy:40,rotation:90,pattern:"scatter",ease:"back",order:"random"});

    function ease(t, kind) {
        t = clamp(t, 0, 1);
        if (t === 0 || t === 1) { return t; }
        if (kind === "linear") { return t; }
        if (kind === "smooth") { return t*t*(3-2*t); }
        if (kind === "quint") { return 1-Math.pow(1-t,5); }
        if (kind === "expo") { return 1-Math.pow(2,-10*t); }
        if (kind === "back") { var b=t-1; return 1+2.70158*b*b*b+1.70158*b*b; }
        if (kind === "elastic") { return Math.pow(2,-10*t)*Math.sin((t*10-0.75)*(2*Math.PI/3))+1; }
        if (kind === "bounce") {
            var n=7.5625, d=2.75;
            if(t<1/d){return n*t*t;}
            if(t<2/d){t-=1.5/d;return n*t*t+0.75;}
            if(t<2.5/d){t-=2.25/d;return n*t*t+0.9375;}
            t-=2.625/d;return n*t*t+0.984375;
        }
        if (kind === "step") { return 1; }
        if (kind === "steps") { return Math.floor(t*6)/6; }
        return 1-Math.pow(1-t,3);
    }
    function orderRank(index, total, kind, seed) {
        var i=index, n=Math.max(1,total), mid=(n-1)/2;
        if (kind === "reverse") { return n-1-i; }
        if (kind === "center") { return Math.abs(i-mid); }
        if (kind === "edges") { return mid-Math.abs(i-mid); }
        if (kind === "together") { return 0; }
        if (kind === "random") { return hash(i,seed)*(n-1); }
        return i;
    }
    function rankSpan(total, kind) {
        if(kind === "together"){return 0;}
        if(kind === "center" || kind === "edges"){return Math.floor((total-1)/2);}
        return Math.max(0,total-1);
    }
    function sample(p, progress, index, total, seed, intensity, easing) {
        var t=clamp(progress,0,1), e=ease(t,easing || p.ease), rem=1-e;
        var a=intensity/100, side=index%2===0?-1:1, norm=total<=1?0:(index/(total-1)*2-1);
        var dx=p.x,dy=p.y,rot=p.rotation,extraX=0,extraY=0;
        if(p.pattern === "alternate"){dx*=side;dy*=side;rot*=side;}
        if(p.pattern === "scatter"){dx*=hash(index,seed)*2-1;dy*=hash(index+91,seed)*2-1;rot*=hash(index+173,seed)*2-1;}
        if(p.pattern === "converge"){dx*=norm;}
        if(p.pattern === "fan"){dx*=norm;dy*=Math.abs(norm);rot*=norm;}
        if(p.pattern === "spiral"){
            var ang=(1-t)*Math.PI*2+index*0.42;
            dx=p.x*Math.cos(ang);dy=p.y*Math.sin(ang);
        }
        if(p.pattern === "wave"){extraY=Math.sin(t*Math.PI*4+index*0.5)*Math.sin(Math.PI*t)*(1-t)*p.wave;}
        if(p.pattern === "arc"){extraY=-Math.sin(Math.PI*t)*p.wave;}
        if(p.pattern === "zigzag"){extraX=Math.sin(t*Math.PI*6)*Math.sin(Math.PI*t)*(1-t)*p.wave;}
        if(p.pattern === "glitch"){
            var tick=Math.floor(t*18);
            dx*=hash(index+tick*13,seed)*2-1;dy*=hash(index+tick*13+47,seed)*2-1;
            rot*=hash(index+tick*13+93,seed)*2-1;
        }
        var opacity=clamp(t*4,0,1);
        if((easing || p.ease)==="step"){opacity=t>0?1:0;}
        if((easing || p.ease)==="steps"){opacity=Math.ceil(t*6)/6;}
        if(p.pattern==="glitch" || p.pattern==="flicker"){
            if(t>0 && t<0.8){opacity*=hash(index+Math.floor(t*24)*17,seed)>0.32?1:0.12;}
        }
        return {x:(dx*rem+extraX)*a,y:(dy*rem+extraY)*a,
            sx:100+(p.sx-100)*rem*a,sy:100+(p.sy-100)*rem*a,
            rotation:rot*rem*a,skew:clamp(p.skew*rem*a,-80,80),
            blur:Math.max(0,p.blur*(1-clamp(e,0,1))*a),opacity:clamp(opacity,0,1)};
    }
    function timing(t, start, duration, stagger, index, total, order, seed, phase, fitEnd) {
        var rank=orderRank(index,total,order,seed), d=Math.max(0.000001,duration), s=Math.max(0,stagger);
        if(order==="center"){rank-=total%2===0?0.5:0;}
        var span=rankSpan(total,order), length=d+s*span;
        if(fitEnd!==null && start+length>fitEnd){
            var f=Math.max(0.001,(fitEnd-start)/length);d*=f;s*=f;
        }
        var u=clamp((t-start-rank*s)/d,0,1);
        if(u<0.0000001){u=0;}else if(u>0.9999999){u=1;}
        return phase==="OUT"?1-u:u;
    }
    function channels(p) {
        var result=["opacity"];
        if(p.x || p.y || p.wave){result.push("position");}
        if(p.sx!==100 || p.sy!==100){result.push("scale");}
        if(p.rotation){result.push("rotation");}
        if(p.skew){result.push("skew");}
        if(p.blur){result.push("blur");}
        return result;
    }
    function literal(p) {
        var keys=["x","y","sx","sy","rotation","skew","blur","ease","pattern","wave"], s=[],i,k,v;
        for(i=0;i<keys.length;i++){k=keys[i];v=p[k];s.push(k+":"+(typeof v==="string"?'"'+v+'"':String(v)));}
        return "{"+s.join(",")+"}";
    }
    function expression(p, channel, phase, options) {
        var prefix=(options.prefix || "YTM ")+phase+" | ";
        var code=["// Yu Text Motion 1.0 | "+p.name+" | "+phase,
            clamp.toString(),hash.toString(),ease.toString(),orderRank.toString(),rankSpan.toString(),sample.toString(),timing.toString(),
            "var p="+literal(p)+";",
            'var d=Math.max(0.01,effect("'+prefix+'Duration")(1));',
            'var s=Math.max(0,effect("'+prefix+'Stagger")(1));',
            'var a=clamp(effect("'+prefix+'Intensity")(1),0,200);',
            'var seed=Math.round(effect("'+prefix+'Seed")(1));',
            'var offset=effect("'+prefix+'Offset")(1);',
            'var n=textTotal, i=textIndex-1, order="'+options.order+'";',
            options.group==="all"?"n=1;i=0;":"",
            "var span=d+s*rankSpan(n,order);",
            "var stop=outPoint-thisComp.frameDuration;",
            "var available=Math.max(thisComp.frameDuration,stop-inPoint);",
            "var budget=available*"+(options.mode==="BOTH"?"0.45":"1")+";",
            "if(span>budget){var factor=budget/span;d*=factor;s*=factor;span=budget;}"];
        if(options.placement==="playhead" && options.mode!=="BOTH"){
            if(phase==="IN" || options.mode==="OUT"){code.push("var start="+Number(options.playhead)+"+offset;");}
            else {code.push("var start=stop-span+offset;");}
        } else {code.push("var start="+(phase==="IN"?"inPoint":"stop-span")+"+offset;");}
        code.push("var u=timing(time,start,d,s,i,n,order,seed,\""+phase+"\",stop);");
        code.push('var v=sample(p,u,i,n,seed,a,"'+(options.easing==="preset"?p.ease:options.easing)+'");');
        var end={opacity:"(1-v.opacity)*100;",position:"[v.x,v.y,0];",scale:"[100-v.sx,100-v.sy,0];",rotation:"v.rotation/10;",skew:"v.skew/0.8;",blur:"[v.blur,v.blur,0];"};
        code.push(end[channel]);return code.join("\n");
    }
    return {presets:presets,clamp:clamp,hash:hash,ease:ease,orderRank:orderRank,rankSpan:rankSpan,
        sample:sample,timing:timing,channels:channels,expression:expression};
}());

/* AE adapter. Reacquire property references after all indexed-group mutations. */
var YTMHost = (function () {
    function starts(s,p){return s.indexOf(p)===0;}
    function animators(layer){return layer.property("ADBE Text Properties").property("ADBE Text Animators");}
    function effects(layer){return layer.property("ADBE Effect Parade");}
    function isText(layer){try{return !!layer.property("ADBE Text Properties");}catch(e){return false;}}
    function removePrefix(layer,prefix){
        var group=animators(layer),i;
        for(i=group.numProperties;i>=1;i--){if(starts(group.property(i).name,prefix)){group.property(i).remove();}}
        group=effects(layer);
        for(i=group.numProperties;i>=1;i--){if(starts(group.property(i).name,prefix)){group.property(i).remove();}}
    }
    function copy(o){var n={},k;for(k in o){if(o.hasOwnProperty(k)){n[k]=o[k];}}return n;}
    function addSlider(layer,name,value){
        /* MotionAstra: compact settings are embedded by expression adapter. */
    }
    function setVector(prop,value){
        var dims=prop.value instanceof Array?prop.value.length:0;
        prop.setValue(dims?value.slice(0,dims):value);
    }
    function addChannel(layer,p,channel,phase,options){
        var a=animators(layer).addProperty("ADBE Text Animator"),ai=a.propertyIndex;
        a.name=options.prefix+phase+" | "+p.name+" | "+channel;
        var match={opacity:"ADBE Text Opacity",position:"ADBE Text Position 3D",scale:"ADBE Text Scale 3D",rotation:"ADBE Text Rotation",skew:"ADBE Text Skew",blur:"ADBE Text Blur"};
        var base={opacity:0,position:[100,100,0],scale:[0,0,100],rotation:1000,skew:80,blur:[100,100]};
        var props=animators(layer).property(ai).property("ADBE Text Animator Properties");
        if(!props.canAddProperty(match[channel])){throw new Error("AE tidak menyediakan "+match[channel]);}
        var prop=props.addProperty(match[channel]);
        if(base[channel] instanceof Array){setVector(prop,base[channel]);}else{prop.setValue(base[channel]);}
        var sels=animators(layer).property(ai).property("ADBE Text Selectors"),i;
        for(i=sels.numProperties;i>=1;i--){sels.property(i).remove();}
        var sel=animators(layer).property(ai).property("ADBE Text Selectors").addProperty("ADBE Text Expressible Selector");
        var si=sel.propertyIndex;
        sel.name="Yu timing";
        var based=sel.property("ADBE Text Range Type2");
        if(!based){throw new Error("Based On tidak ditemukan pada Expression Selector.");}
        based.setValue({chars:1,charsNoSpaces:2,words:3,lines:4,all:1}[options.group]);
        var amount=animators(layer).property(ai).property("ADBE Text Selectors").property(si).property("ADBE Text Expressible Amount");
        if(!amount || !amount.canSetExpression){throw new Error("Expression Selector tidak dapat ditulis.");}
        amount.expression=YTMCore.expression(p,channel,phase,options);
        amount.expressionEnabled=true;
        if(amount.expressionError){throw new Error(amount.expressionError);}
    }
    function apply(layer,p,options){
        if(!isText(layer)){throw new Error("Pilih text layer.");}
        if(layer.locked){throw new Error("Layer terkunci.");}
        var comp=layer.containingComp;
        if(layer.outPoint-layer.inPoint<=2*comp.frameDuration){throw new Error("Layer harus lebih panjang dari dua frame.");}
        if(options.placement==="playhead" && options.mode!=="BOTH" &&
            (options.playhead<layer.inPoint || options.playhead>=layer.outPoint-comp.frameDuration)){
            throw new Error("Playhead harus berada di dalam durasi layer.");
        }
        var opt=copy(options),token="YTM TEMP "+(new Date().getTime())+" ",phases=options.mode==="BOTH"?["IN","OUT"]:[options.mode];
        opt.prefix=token;
        var ch=YTMCore.channels(p),i,j,phase,prefix,group,name,suffix,amount;
        try {
            for(i=0;i<phases.length;i++){
                phase=phases[i];prefix=token+phase+" | ";
                addSlider(layer,prefix+"Duration",options.duration);
                addSlider(layer,prefix+"Stagger",options.stagger);
                addSlider(layer,prefix+"Intensity",options.intensity);
                addSlider(layer,prefix+"Seed",options.seed);
                addSlider(layer,prefix+"Offset",0);
                for(j=0;j<ch.length;j++){addChannel(layer,p,ch[j],phase,opt);}
            }
        }catch(e){removePrefix(layer,token);throw e;}
        // Existing IN / OUT remains intact until all new properties can be created.
        for(i=0;i<phases.length;i++){removePrefix(layer,"YTM "+phases[i]+" | ");}
        group=effects(layer);
        for(i=1;i<=group.numProperties;i++){
            if(starts(group.property(i).name,token)){group.property(i).name="YTM "+group.property(i).name.substr(token.length);}
        }
        opt.prefix="YTM ";group=animators(layer);
        for(i=1;i<=group.numProperties;i++){
            name=group.property(i).name;
            if(starts(name,token)){
                suffix=name.substr(token.length);phase=suffix.split(" | ")[0];
                var parts=suffix.split(" | "),channel=parts[parts.length-1];
                group.property(i).name="YTM "+suffix;
                amount=group.property(i).property("ADBE Text Selectors").property(1).property("ADBE Text Expressible Amount");
                amount.expression=YTMCore.expression(p,channel,phase,opt);
            }
        }
    }
    function clear(layer){removePrefix(layer,"YTM IN | ");removePrefix(layer,"YTM OUT | ");}
    function selected(){
        var comp=app.project.activeItem;
        if(!(comp instanceof CompItem)){throw new Error("Buka composition terlebih dahulu.");}
        var list=comp.selectedLayers,result=[],i;
        for(i=0;i<list.length;i++){if(isText(list[i])){result.push(list[i]);}}
        if(!result.length){throw new Error("Pilih satu atau beberapa text layer di timeline.");}
        return {comp:comp,layers:result};
    }
    function makeText(comp,text,size,position){
        var l=comp.layers.addText(text),prop=l.property("ADBE Text Properties").property("ADBE Text Document"),doc=prop.value;
        doc.fontSize=size;doc.applyFill=true;doc.fillColor=[1,1,1];doc.applyStroke=false;
        doc.justification=ParagraphJustification.CENTER_JUSTIFY;
        prop.setValue(doc);
        var rect=l.sourceRectAtTime(comp.time,false);
        l.property("ADBE Transform Group").property("ADBE Anchor Point").setValue([rect.left+rect.width/2,rect.top+rect.height/2]);
        l.property("ADBE Transform Group").property("ADBE Position").setValue(position);
        return l;
    }
    function demo(p,options){
        var comp=app.project.items.addComp("Yu Preview - "+p.name,1920,1080,1,6,30);
        comp.bgColor=[0.04,0.055,0.085];
        var text=makeText(comp,"YU GRAPHIC",140,[960,510]);text.name="Preview - "+p.name;text.inPoint=0.3;text.outPoint=5.7;
        var caption=makeText(comp,p.name+"  /  "+p.category,32,[960,720]);caption.name="Preset label";
        var opt=copy(options);opt.mode="BOTH";opt.placement="edges";opt.playhead=0;
        apply(text,p,opt);comp.time=0.3;comp.openInViewer();caption.selected=false;text.selected=true;
        return comp;
    }
    return {apply:apply,clear:clear,selected:selected,makeText:makeText,demo:demo,isText:isText};
}());

/* MotionAstra integration. Original YUGraphic motion math is unchanged. */
var originalExpression = YTMCore.expression,
  currentOptions = null;
YTMCore.expression = function (p, channel, phase, options) {
  var expression = originalExpression(p, channel, phase, options);
  var values = {
    Duration: currentOptions.duration,
    Stagger: currentOptions.stagger,
    Intensity: currentOptions.intensity,
    Seed: currentOptions.seed,
    Offset: 0
  };
  return expression.replace(
    /effect\("[^"\n]+ \| (Duration|Stagger|Intensity|Seed|Offset)"\)\(1\)/g,
    function (all, key) {
      return "(" + values[key] + ")";
    }
  );
};
function choose(value, list, label) {
  for (var i = 0; i < list.length; i++) if (value === list[i]) return value;
  throw Error("Invalid YU " + label + ".");
}
function numeric(value, min, max, label) {
  if (
    typeof value !== "number" ||
    !isFinite(value) ||
    value < min ||
    value > max
  )
    throw Error("Invalid YU " + label + ". Expected " + min + "–" + max + ".");
  return value;
}
function options(a) {
  return {
    mode: choose(a.mode, ["IN", "OUT", "BOTH"], "mode"),
    duration: numeric(a.duration, 0.01, 10, "duration"),
    stagger: numeric(a.stagger, 0, 2, "stagger"),
    intensity: numeric(a.intensity, 0, 200, "intensity"),
    seed: Math.round(numeric(a.seed, 0, 99999, "seed")),
    group: choose(
      a.group,
      ["chars", "charsNoSpaces", "words", "lines", "all"],
      "group"
    ),
    order: choose(
      a.order,
      ["forward", "reverse", "center", "edges", "random", "together"],
      "order"
    ),
    easing: choose(
      a.easing,
      [
        "preset",
        "smooth",
        "cubic",
        "quint",
        "expo",
        "back",
        "bounce",
        "elastic",
        "linear",
        "step",
        "steps"
      ],
      "easing"
    ),
    placement: choose(a.placement, ["edges", "playhead"], "placement"),
    playhead: 0
  };
}
var recordPattern = /\n?\[MA_YU\]([^\r\n]*)\[\/MA_YU\]/;
function read(layer, codec) {
  var m = String(layer.comment || "").match(recordPattern);
  return m ? codec.parse(m[1]) : null;
}
function write(layer, m, codec) {
  layer.comment =
    String(layer.comment || "").replace(recordPattern, "") +
    "\n[MA_YU]" +
    codec.encode(m) +
    "[/MA_YU]";
}
function identity(c, l, m) {
  return {
    comp: typeof c.id === "number" ? c.id : c.name,
    layer: typeof l.id === "number" ? l.id : l.index,
    token: m.token
  };
}
function clear(layer) {
  if (!YTMHost.isText(layer)) return;
  YTMHost.clear(layer);
  layer.comment = String(layer.comment || "").replace(recordPattern, "");
}
// Replacing a phase must not silently discard animation authored in AE.
function knownChannel(p, channel) {
  var list = YTMCore.channels(p), i;
  for (i = 0; i < list.length; i++) if (list[i] === channel) return true;
  return false;
}
function sameExpression(a, b) {
  return String(a).replace(/\r\n?/g, "\n") === String(b).replace(/\r\n?/g, "\n");
}
function generatedPhaseExpression(entry, phase, channel) {
  var opt = {}, key;
  for (key in entry.options) if (entry.options.hasOwnProperty(key)) opt[key] = entry.options[key];
  opt.prefix = "YTM "; currentOptions = opt;
  try { return YTMCore.expression(YTMCore.presets[entry.id - 1], channel, phase, opt); }
  finally { currentOptions = null; }
}
function protectPhase(layer, metadata, mode, copySelectors) {
  var groups = [layer.property("ADBE Text Properties").property("ADBE Text Animators"), layer.property("ADBE Effect Parade")], i, j, g, parts, phase, entry, expected, oldOptions, key;
  function custom(prop, allowed, copiedAmount) {
    if (prop.numKeys) return true;
    // AE may persist generated expressions with Windows CRLF or legacy CR line endings.
    // Normalize only line separators: authored code and keyframes remain protected.
    if (prop !== copiedAmount && prop.canSetExpression && prop.expression && !sameExpression(prop.expression, allowed)) return true;
    for (var n = 1; n <= (prop.numProperties || 0); n++) if (custom(prop.property(n), allowed, copiedAmount)) return true;
    return false;
  }
  for (i = 0; i < groups.length; i++) for (j = 1; j <= groups[i].numProperties; j++) {
    g = groups[i].property(j); parts = g.name.split(" | ");
    phase = parts[0] === "YTM IN" ? "IN" : parts[0] === "YTM OUT" ? "OUT" : null;
    if (!phase || (mode !== "BOTH" && mode !== phase)) continue;
    entry = metadata && metadata[phase]; expected = "";
    if (entry && parts.length === 3 && YTMCore.presets[entry.id - 1]) {
      oldOptions = {}; for (key in entry.options) if (entry.options.hasOwnProperty(key)) oldOptions[key] = entry.options[key];
      oldOptions.prefix = "YTM "; currentOptions = oldOptions;
      try { expected = YTMCore.expression(YTMCore.presets[entry.id - 1], parts[2], phase, oldOptions); }
      finally { currentOptions = null; }
    }
    var copiedAmount = null;
    // Copy may transport only this preset's known selector Amount, never other expressions.
    if (copySelectors && i === 0 && entry && parts.length === 3 &&
      YTMCore.presets[entry.id - 1] && parts[1] === YTMCore.presets[entry.id - 1].name &&
      knownChannel(YTMCore.presets[entry.id - 1], parts[2])) {
      copiedAmount = g.property("ADBE Text Selectors").property(1).property("ADBE Text Expressible Amount");
    }
    if (custom(g, expected, copiedAmount)) throw Error("This " + phase + " animation has custom keyframes or expressions. Edit it in AE, or explicitly remove the animation before replacing it.");
  }
}
function run(a, codec) {
  var c = app.project.activeItem;
  if (!(c instanceof CompItem))
    throw Error("Open a composition before using YU Txt Motion.");
  var list = c.selectedLayers,
    i,
    l,
    m,
    p,
    opt,
    count = 0,
    lines = [],
    phase,
    target,
    actual;
  if (a.operation === "load") {
    if (list.length !== 1 || !YTMHost.isText(list[0]))
      throw Error("Select one YU text layer to load.");
    l = list[0];
    m = read(l, codec);
    if (!m)
      throw Error(
        "No YU Txt Motion settings on the selected layer. Apply a YU preset first."
      );
    if (a.target) {
      actual = identity(c, l, m);
      if (actual.comp !== a.target.comp || actual.layer !== a.target.layer || actual.token !== a.target.token)
        throw Error("Selection changed. Load animation settings again.");
    }
    phase = a.phase === "OUT" ? "OUT" : "IN";
    var entry = a.phase ? m[phase] : (m.IN || m.OUT);
    if (!a.phase && !m.IN) phase = "OUT";
    if (!entry) throw Error("No saved YU settings.");
    var loadedOptions = codec.parse(codec.encode(entry.options));
    loadedOptions.mode = phase;
    return {
      ok: true,
      id: entry.id,
      options: loadedOptions,
      target: identity(c, l, m),
      revision: codec.encode(m),
      layerName: l.name,
      message: "Loaded YU settings from " + l.name + "."
    };
  }
  if (a.operation !== "apply" && a.operation !== "clear")
    throw Error("Unknown YU action.");
  if (!list.length) throw Error("Select one or more text layers.");
  if (a.target) {
    if (list.length !== 1)
      throw Error("Select the loaded YU layer only, or load again.");
    m = read(list[0], codec);
    actual = m ? identity(c, list[0], m) : null;
    target = a.target;
    if (a.revision !== undefined && codec.encode(m) !== a.revision)
      throw Error("Animation settings changed. Load selected settings again.");
    if (
      !actual ||
      actual.comp !== target.comp ||
      actual.layer !== target.layer ||
      actual.token !== target.token
    )
      throw Error("Selection changed. Load YU settings again before updating.");
  }
  if (a.operation === "apply") {
    if (app.project.expressionEngine !== "javascript-1.0")
      throw Error("Use Project Settings → Expressions → JavaScript.");
    var id = numeric(a.id, 1, YTMCore.presets.length, "preset ID");
    if (id !== Math.floor(id)) throw Error("Invalid YU preset ID.");
    p = YTMCore.presets[id - 1];
    opt = options(a.options || {});
    opt.playhead = c.time;
  }
  for (i = 0; i < list.length; i++) {
    l = list[i];
    try {
      if (!YTMHost.isText(l)) throw Error("Text layers only.");
      if (l.locked) throw Error("Layer is locked.");
      if (a.operation === "clear") {
        clear(l);
        count++;
        continue;
      }
      m = read(l, codec) || { token: "yu_" + new Date().getTime() + "_" + i };
      protectPhase(l, m, opt.mode);
      currentOptions = opt;
      YTMHost.apply(l, p, opt);
      currentOptions = null;
      if (opt.mode === "IN" || opt.mode === "BOTH")
        m.IN = { id: p.id, options: opt };
      if (opt.mode === "OUT" || opt.mode === "BOTH")
        m.OUT = { id: p.id, options: opt };
      write(l, m, codec);
      count++;
    } catch (e) {
      currentOptions = null;
      lines.push(l.name + ": " + String(e));
    }
  }
  var message =
    (a.operation === "clear"
      ? "Removed YU animation from "
      : p.name + " applied to ") +
    count +
    " text layer(s).";
  if (lines.length)
    message +=
      "\n" +
      lines.join("\n") +
      "\nCheck the timeline; Undo once if an operation partially changed it.";
  return {
    ok: true,
    changed: count,
    severity: lines.length ? "warning" : "success",
    message: message
  };
}
// Session clipboard carries known phase settings plus explicitly authorized selector overrides.
function copyPhaseExpressions(layer, entry, phase) {
  var p = YTMCore.presets[entry.id - 1], channels = YTMCore.channels(p), i, g, amount, result = [];
  var group = layer.property("ADBE Text Properties").property("ADBE Text Animators");
  for (i = 0; i < channels.length; i++) {
    g = group.property("YTM " + phase + " | " + p.name + " | " + channels[i]);
    if (!g) throw Error("Missing Text Animate selector: " + channels[i]);
    amount = g.property("ADBE Text Selectors").property(1).property("ADBE Text Expressible Amount");
    if (!sameExpression(amount.expression, generatedPhaseExpression(entry, phase, channels[i])) ||
      amount.expressionEnabled === false) {
      result.push({channel: channels[i], expression: String(amount.expression || ""), enabled: !!amount.expressionEnabled});
    }
  }
  return result;
}
function copyMotion(layer, codec) {
  var m = read(layer, codec), result = [], i, phase, entry, opt, doc, text, n, span, budget, start;
  if (!m) return result;
  doc = layer.property("ADBE Text Properties").property("ADBE Text Document").value;
  text = String(doc.text || "");
  for (i = 0; i < 2; i++) {
    phase = i ? "OUT" : "IN"; entry = m[phase]; if (!entry) continue;
    if (!YTMCore.presets[entry.id - 1]) throw Error("Unknown Text Animate preset.");
    protectPhase(layer, m, phase, true); opt = codec.parse(codec.encode(entry.options)); options(opt);
    n = opt.group === "all" ? 1 : opt.group === "words" ? (text.match(/\S+/g) || []).length :
      opt.group === "lines" ? (doc.composedLineCount || text.split(/\r\n|\r|\n/).length) :
      opt.group === "charsNoSpaces" ? text.replace(/\s/g, "").length : text.length;
    span = opt.duration + opt.stagger * YTMCore.rankSpan(Math.max(1, n), opt.order);
    budget = Math.max(layer.containingComp.frameDuration, layer.outPoint - layer.containingComp.frameDuration - layer.inPoint) * (opt.mode === "BOTH" ? .45 : 1);
    span = Math.min(span, budget);
    start = opt.placement === "playhead" && opt.mode !== "BOTH" ? opt.playhead : phase === "IN" ? layer.inPoint : layer.outPoint - layer.containingComp.frameDuration - span;
    result.push({id: entry.id, phase: phase, options: opt, time: start, expressions: copyPhaseExpressions(layer, entry, phase)});
  }
  return result;
}
function validateMotion(entries) {
  var used = {}, i, e, j, overrides, channels, override;
  for (i = 0; i < entries.length; i++) {
    e = entries[i];
    if (!e || typeof e.id !== "number" || e.id !== Math.floor(e.id) || !YTMCore.presets[e.id - 1] ||
      (e.phase !== "IN" && e.phase !== "OUT") || used[e.phase] || typeof e.time !== "number" || !isFinite(e.time) || e.time < 0)
      throw Error("Invalid copied Text Animate motion.");
    options(e.options); used[e.phase] = true;
    if (e.expressions !== undefined) {
      if (!(e.expressions instanceof Array) || e.expressions.length > YTMCore.channels(YTMCore.presets[e.id - 1]).length)
        throw Error("Invalid copied selector expressions.");
      channels = {};
      for (j = 0; j < e.expressions.length; j++) {
        override = e.expressions[j];
        if (!override || !knownChannel(YTMCore.presets[e.id - 1], override.channel) ||
          channels[override.channel] || typeof override.expression !== "string" ||
          override.expression.length > 1000000 || typeof override.enabled !== "boolean")
          throw Error("Invalid copied selector expression.");
        channels[override.channel] = true;
      }
    }
  }
}
function pasteMotion(layer, entries, start, codec) {
  validateMotion(entries);
  var i, j, e, opt, override, amount, animator, m = {token: "yu_" + new Date().getTime() + "_paste"};
  try {
    for (i = 0; i < entries.length; i++) {
      e = entries[i]; opt = options(e.options); opt.mode = e.phase; opt.placement = "playhead"; opt.playhead = start + e.time;
      currentOptions = opt;
      try { YTMHost.apply(layer, YTMCore.presets[e.id - 1], opt); }
      finally { currentOptions = null; }
      for (j = 0; j < (e.expressions || []).length; j++) {
        override = e.expressions[j];
        animator = layer.property("ADBE Text Properties").property("ADBE Text Animators")
          .property("YTM " + e.phase + " | " + YTMCore.presets[e.id - 1].name + " | " + override.channel);
        amount = animator.property("ADBE Text Selectors").property(1).property("ADBE Text Expressible Amount");
        amount.expression = override.expression;
        amount.expressionEnabled = override.enabled;
      }
      m[e.phase] = {id: e.id, options: opt};
    }
    write(layer, m, codec);
  } catch (error) { clear(layer); throw error; }
}
return {run: run, clear: clear, copyMotion: copyMotion, pasteMotion: pasteMotion, validateMotion: validateMotion, motionVersion: 1};

}());

MotionAstraYU.build='1.0.0';
if(typeof $!=="undefined"&&$.global){$.global.MotionAstraYU=MotionAstraYU;$.global.MotionAstraModules=$.global.MotionAstraModules||{};$.global.MotionAstraModules.yuText=MotionAstraYU;}
