"""Build the isolated Media registry and ES3 host; never alters Text/SolidGen data."""
from pathlib import Path
import json
root = Path(__file__).resolve().parent.parent
data = json.loads((root / 'media-presets.json').read_text())
wire = json.dumps(data, ensure_ascii=True, separators=(',', ':'))
(root / 'js/media-presets-data.js').write_text('/* Generated by tools/build-media.py */\nwindow.ZXT_MEDIA_PRESETS=' + wire + ';\n')
source = '/* Generated by tools/build-media.py; edit src/media-host.js */\nvar ZxTMedia=(function(){var registry=' + wire + ';\n' + (root / 'src/media-host.js').read_text() + '\n}());\n'
source += 'ZxTMedia.build=' + json.dumps((root/'VERSION').read_text().strip()) + ';\n'
source += 'if(typeof $!=="undefined"&&$.global){$.global.MotionAstraModules=$.global.MotionAstraModules||{};$.global.MotionAstraModules.mediaLibrary=ZxTMedia;}\n'
(root / 'jsx/media.jsx').write_text(source)
