"""Build the isolated Shape registry and ES3 host; never alters Text/SolidGen data."""
from pathlib import Path
import json
root = Path(__file__).resolve().parent.parent
data = json.loads((root / 'shape-presets.json').read_text())
wire = json.dumps(data, ensure_ascii=True, separators=(',', ':'))
(root / 'js/shape-presets-data.js').write_text('/* Generated by tools/build-shape.py */\nwindow.ZXT_SHAPE_PRESETS=' + wire + ';\n')
source = '/* Generated by tools/build-shape.py; edit src/shape-host.js */\nvar ZxTShape=(function(){var registry=' + wire + ';\n' + (root / 'src/shape-host.js').read_text() + '\n}());\n'
source += 'ZxTShape.build=' + json.dumps((root/'VERSION').read_text().strip()) + ';\n'
source += 'if(typeof $!=="undefined"&&$.global){$.global.MotionAstraModules=$.global.MotionAstraModules||{};$.global.MotionAstraModules.shapeLibrary=ZxTShape;}\n'
(root / 'jsx/shape.jsx').write_text(source)
